/* AUTO-GENERATED by nds_recompile. DO NOT EDIT. */
#ifndef POR_ARM9_022E5000_6E2F7FF5_H
#define POR_ARM9_022E5000_6E2F7FF5_H

/* Total functions: 33 */

void por_arm9_022e5000_6e2f7ff5_afunc_022E5340(void);  /* 0x022E5340 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E536C(void);  /* 0x022E536C arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5370(void);  /* 0x022E5370 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5374(void);  /* 0x022E5374 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5378(void);  /* 0x022E5378 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E53A0(void);  /* 0x022E53A0 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E53AC(void);  /* 0x022E53AC arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E53BC(void);  /* 0x022E53BC arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E53C0(void);  /* 0x022E53C0 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E53C4(void);  /* 0x022E53C4 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E53C8(void);  /* 0x022E53C8 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E53D4(void);  /* 0x022E53D4 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5400(void);  /* 0x022E5400 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5424(void);  /* 0x022E5424 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5494(void);  /* 0x022E5494 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E54A8(void);  /* 0x022E54A8 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E54AC(void);  /* 0x022E54AC arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E54B0(void);  /* 0x022E54B0 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E54B4(void);  /* 0x022E54B4 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E58E0(void);  /* 0x022E58E0 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E58F0(void);  /* 0x022E58F0 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5918(void);  /* 0x022E5918 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5920(void);  /* 0x022E5920 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5928(void);  /* 0x022E5928 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5944(void);  /* 0x022E5944 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E594C(void);  /* 0x022E594C arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5950(void);  /* 0x022E5950 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E595C(void);  /* 0x022E595C arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5964(void);  /* 0x022E5964 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5974(void);  /* 0x022E5974 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E597C(void);  /* 0x022E597C arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5980(void);  /* 0x022E5980 arm */
void por_arm9_022e5000_6e2f7ff5_afunc_022E5988(void);  /* 0x022E5988 arm */

#endif /* POR_ARM9_022E5000_6E2F7FF5_H */
