/* AUTO-GENERATED by nds_recompile. DO NOT EDIT. */
#ifndef POR_ARM9_022ED000_F7620BC8_H
#define POR_ARM9_022ED000_F7620BC8_H

/* Total functions: 74 */

void por_arm9_022ed000_f7620bc8_afunc_022ED880(void);  /* 0x022ED880 arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED89C(void);  /* 0x022ED89C arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED8BC(void);  /* 0x022ED8BC arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED8CC(void);  /* 0x022ED8CC arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED8D4(void);  /* 0x022ED8D4 arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED8DC(void);  /* 0x022ED8DC arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED95C(void);  /* 0x022ED95C arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED960(void);  /* 0x022ED960 arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED988(void);  /* 0x022ED988 arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED9B8(void);  /* 0x022ED9B8 arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED9BC(void);  /* 0x022ED9BC arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED9C0(void);  /* 0x022ED9C0 arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED9CC(void);  /* 0x022ED9CC arm */
void por_arm9_022ed000_f7620bc8_afunc_022ED9F8(void);  /* 0x022ED9F8 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA00(void);  /* 0x022EDA00 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA08(void);  /* 0x022EDA08 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA30(void);  /* 0x022EDA30 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA38(void);  /* 0x022EDA38 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA60(void);  /* 0x022EDA60 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA80(void);  /* 0x022EDA80 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA84(void);  /* 0x022EDA84 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA88(void);  /* 0x022EDA88 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA8C(void);  /* 0x022EDA8C arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA90(void);  /* 0x022EDA90 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA98(void);  /* 0x022EDA98 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDA9C(void);  /* 0x022EDA9C arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDAD4(void);  /* 0x022EDAD4 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDAE8(void);  /* 0x022EDAE8 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDAEC(void);  /* 0x022EDAEC arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDAF4(void);  /* 0x022EDAF4 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDAFC(void);  /* 0x022EDAFC arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDB04(void);  /* 0x022EDB04 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDB10(void);  /* 0x022EDB10 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDB20(void);  /* 0x022EDB20 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDB34(void);  /* 0x022EDB34 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDB3C(void);  /* 0x022EDB3C arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDB50(void);  /* 0x022EDB50 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDB60(void);  /* 0x022EDB60 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDB84(void);  /* 0x022EDB84 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDB90(void);  /* 0x022EDB90 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDBAC(void);  /* 0x022EDBAC arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDBB8(void);  /* 0x022EDBB8 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDBDC(void);  /* 0x022EDBDC arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDBEC(void);  /* 0x022EDBEC arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDC04(void);  /* 0x022EDC04 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDC0C(void);  /* 0x022EDC0C arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDC3C(void);  /* 0x022EDC3C arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDC48(void);  /* 0x022EDC48 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDC74(void);  /* 0x022EDC74 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDC78(void);  /* 0x022EDC78 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDC84(void);  /* 0x022EDC84 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDC88(void);  /* 0x022EDC88 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDCA0(void);  /* 0x022EDCA0 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDCB0(void);  /* 0x022EDCB0 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDCC0(void);  /* 0x022EDCC0 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDCC8(void);  /* 0x022EDCC8 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDCEC(void);  /* 0x022EDCEC arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDCFC(void);  /* 0x022EDCFC arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDD10(void);  /* 0x022EDD10 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDD44(void);  /* 0x022EDD44 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDD48(void);  /* 0x022EDD48 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDD58(void);  /* 0x022EDD58 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDD7C(void);  /* 0x022EDD7C arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDDA0(void);  /* 0x022EDDA0 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDDB0(void);  /* 0x022EDDB0 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDDC0(void);  /* 0x022EDDC0 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDDC4(void);  /* 0x022EDDC4 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDDD8(void);  /* 0x022EDDD8 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDE1C(void);  /* 0x022EDE1C arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDEDC(void);  /* 0x022EDEDC arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDEE8(void);  /* 0x022EDEE8 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDF10(void);  /* 0x022EDF10 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDF48(void);  /* 0x022EDF48 arm */
void por_arm9_022ed000_f7620bc8_afunc_022EDF68(void);  /* 0x022EDF68 arm */

#endif /* POR_ARM9_022ED000_F7620BC8_H */
