/* AUTO-GENERATED by nds_recompile. DO NOT EDIT.
   Each guest function lowers to a void C function over the recomp
   ABI (g_cpu, bus_*, runtime_*; see runtime_arm.h). The interpreter
   is never consulted at runtime — an unlowered op aborts via
   runtime_unimplemented_op (PRINCIPLES.md). */
#include "runtime_arm.h"

void por_arm9_021d5000_23b9ff77_afunc_021D56E0(void);
void por_arm9_021d5000_23b9ff77_afunc_021D56F4(void);
void por_arm9_021d5000_23b9ff77_afunc_021D5700(void);
void por_arm9_021d5000_23b9ff77_afunc_021D5DE8(void);
void por_arm9_021d5000_23b9ff77_afunc_021D5FE4(void);
void por_arm9_021d5000_23b9ff77_afunc_021D5FFC(void);

/* 0x021D56E0  mode=arm  end=0x021D56F4  branches=0  indirect */
void por_arm9_021d5000_23b9ff77_afunc_021D56E0(void) {
    if (g_cpu.R[15] != 0x021D56E0u) {
        switch (g_cpu.R[15]) {
            case 0x021D56E4u: goto L_021D56E4;
            case 0x021D56E8u: goto L_021D56E8;
            case 0x021D56ECu: goto L_021D56EC;
            case 0x021D56F0u: goto L_021D56F0;
            default: runtime_dispatch_bad_entry(g_cpu.R[15]); return;
        }
    }
L_021D56E0:
    /* 021D56E0  021d56e0 A ldr r1,[r15,#0x2c] */
    g_cpu.R[15] = 0x021D56E0u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D56E0 = 1u;
    uint32_t _code_021D56E0 = nds_code_numc(0x021D56E0u, NDS_ARM9_CODE_K(0x021D56E0u, 0));
    uint32_t _data_021D56E0 = 0u;
    uint32_t _int_021D56E0 = 0u;
    _cyc_021D56E0 = 2u;
    _int_021D56E0 = 0u;
    uint32_t _base_021D56E0 = 0x021D56E8u;
    uint32_t _off_021D56E0;
    _off_021D56E0 = 0x0000002Cu;
    uint32_t _ea_021D56E0 = _base_021D56E0 + _off_021D56E0;
    uint32_t _post_021D56E0 = _base_021D56E0 + _off_021D56E0;
    { uint32_t _m = runtime_mem_cycles(_ea_021D56E0, 4u, 0u); _cyc_021D56E0 += _m; _data_021D56E0 += _m; }
    uint32_t _v_021D56E0;
    { uint32_t _w = bus_read_u32(_ea_021D56E0 & ~3u); uint32_t _rot = (_ea_021D56E0 & 3u) * 8u; _v_021D56E0 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[1] = _v_021D56E0;
    g_cpu.R[15] = 0x021D56E4u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D56E0, _data_021D56E0, _int_021D56E0, 1u) : arm7_cycle_combine(_cyc_021D56E0, _data_021D56E0, 1u, (_int_021D56E0 != 0u)));
    if (runtime_unwinding()) return;
L_021D56E4:
    /* 021D56E4  021d56e4 A ldr r2,[r0,#0x158] */
    g_cpu.R[15] = 0x021D56E4u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D56E4 = 1u;
    uint32_t _code_021D56E4 = nds_code_numc(0x021D56E4u, NDS_ARM9_CODE_K(0x021D56E4u, 0));
    uint32_t _data_021D56E4 = 0u;
    uint32_t _int_021D56E4 = 0u;
    _cyc_021D56E4 = 2u;
    _int_021D56E4 = 0u;
    uint32_t _base_021D56E4 = g_cpu.R[0];
    uint32_t _off_021D56E4;
    _off_021D56E4 = 0x00000158u;
    uint32_t _ea_021D56E4 = _base_021D56E4 + _off_021D56E4;
    uint32_t _post_021D56E4 = _base_021D56E4 + _off_021D56E4;
    { uint32_t _m = runtime_mem_cycles(_ea_021D56E4, 4u, 0u); _cyc_021D56E4 += _m; _data_021D56E4 += _m; }
    uint32_t _v_021D56E4;
    { uint32_t _w = bus_read_u32(_ea_021D56E4 & ~3u); uint32_t _rot = (_ea_021D56E4 & 3u) * 8u; _v_021D56E4 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[2] = _v_021D56E4;
    g_cpu.R[15] = 0x021D56E8u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D56E4, _data_021D56E4, _int_021D56E4, 1u) : arm7_cycle_combine(_cyc_021D56E4, _data_021D56E4, 1u, (_int_021D56E4 != 0u)));
    if (runtime_unwinding()) return;
L_021D56E8:
    /* 021D56E8  021d56e8 A ldr r0,[r1] */
    g_cpu.R[15] = 0x021D56E8u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D56E8 = 1u;
    uint32_t _code_021D56E8 = nds_code_numc(0x021D56E8u, NDS_ARM9_CODE_K(0x021D56E8u, 0));
    uint32_t _data_021D56E8 = 0u;
    uint32_t _int_021D56E8 = 0u;
    _cyc_021D56E8 = 2u;
    _int_021D56E8 = 0u;
    uint32_t _base_021D56E8 = g_cpu.R[1];
    uint32_t _off_021D56E8;
    _off_021D56E8 = 0x00000000u;
    uint32_t _ea_021D56E8 = _base_021D56E8 + _off_021D56E8;
    uint32_t _post_021D56E8 = _base_021D56E8 + _off_021D56E8;
    { uint32_t _m = runtime_mem_cycles(_ea_021D56E8, 4u, 0u); _cyc_021D56E8 += _m; _data_021D56E8 += _m; }
    uint32_t _v_021D56E8;
    { uint32_t _w = bus_read_u32(_ea_021D56E8 & ~3u); uint32_t _rot = (_ea_021D56E8 & 3u) * 8u; _v_021D56E8 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[0] = _v_021D56E8;
    g_cpu.R[15] = 0x021D56ECu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D56E8, _data_021D56E8, _int_021D56E8, 1u) : arm7_cycle_combine(_cyc_021D56E8, _data_021D56E8, 1u, (_int_021D56E8 != 0u)));
    if (runtime_unwinding()) return;
L_021D56EC:
    /* 021D56EC  021d56ec A add r0,r0,#0x1b000 */
    g_cpu.R[15] = 0x021D56ECu;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D56EC = 1u;
    uint32_t _code_021D56EC = nds_code_numc(0x021D56ECu, NDS_ARM9_CODE_K(0x021D56ECu, 0));
    uint32_t _data_021D56EC = 0u;
    uint32_t _int_021D56EC = 0u;
    _cyc_021D56EC = 1u;
    _int_021D56EC = 0u;
    uint32_t _rn_021D56EC = g_cpu.R[0];
    uint32_t _r_021D56EC;
    _r_021D56EC = _rn_021D56EC + 0x0001B000u;
    g_cpu.R[0] = _r_021D56EC;
    g_cpu.R[15] = 0x021D56F0u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D56EC, _data_021D56EC, _int_021D56EC, 0u) : arm7_cycle_combine(_cyc_021D56EC, _data_021D56EC, 0u, (_int_021D56EC != 0u)));
    if (runtime_unwinding()) return;
L_021D56F0:
    /* 021D56F0  021d56f0 A ldr r0,[r0,#0xd28] */
    g_cpu.R[15] = 0x021D56F0u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D56F0 = 1u;
    uint32_t _code_021D56F0 = nds_code_numc(0x021D56F0u, NDS_ARM9_CODE_K(0x021D56F0u, 0));
    uint32_t _data_021D56F0 = 0u;
    uint32_t _int_021D56F0 = 0u;
    _cyc_021D56F0 = 2u;
    _int_021D56F0 = 0u;
    uint32_t _base_021D56F0 = g_cpu.R[0];
    uint32_t _off_021D56F0;
    _off_021D56F0 = 0x00000D28u;
    uint32_t _ea_021D56F0 = _base_021D56F0 + _off_021D56F0;
    uint32_t _post_021D56F0 = _base_021D56F0 + _off_021D56F0;
    { uint32_t _m = runtime_mem_cycles(_ea_021D56F0, 4u, 0u); _cyc_021D56F0 += _m; _data_021D56F0 += _m; }
    uint32_t _v_021D56F0;
    { uint32_t _w = bus_read_u32(_ea_021D56F0 & ~3u); uint32_t _rot = (_ea_021D56F0 & 3u) * 8u; _v_021D56F0 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[0] = _v_021D56F0;
    g_cpu.R[15] = 0x021D56F4u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D56F0, _data_021D56F0, _int_021D56F0, 1u) : arm7_cycle_combine(_cyc_021D56F0, _data_021D56F0, 1u, (_int_021D56F0 != 0u)));
    if (runtime_unwinding()) return;
    /* fall-through to 0x021D56F4 */
    g_cpu.R[15] = 0x021D56F4u;
    { static NdsLinkSlot _lnk_021D56F4_f = {0, 0u, 0x021D56F4u, 0};
      runtime_link_fallthrough(&_lnk_021D56F4_f); }
    return;
}

/* 0x021D56F4  mode=arm  end=0x021D5700  branches=0  indirect */
void por_arm9_021d5000_23b9ff77_afunc_021D56F4(void) {
    if (g_cpu.R[15] != 0x021D56F4u) {
        switch (g_cpu.R[15]) {
            case 0x021D56F8u: goto L_021D56F8;
            case 0x021D56FCu: goto L_021D56FC;
            default: runtime_dispatch_bad_entry(g_cpu.R[15]); return;
        }
    }
L_021D56F4:
    /* 021D56F4  021d56f4 A ldr r0,[r0,#0x30] */
    g_cpu.R[15] = 0x021D56F4u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D56F4 = 1u;
    uint32_t _code_021D56F4 = nds_code_numc(0x021D56F4u, NDS_ARM9_CODE_K(0x021D56F4u, 0));
    uint32_t _data_021D56F4 = 0u;
    uint32_t _int_021D56F4 = 0u;
    _cyc_021D56F4 = 2u;
    _int_021D56F4 = 0u;
    uint32_t _base_021D56F4 = g_cpu.R[0];
    uint32_t _off_021D56F4;
    _off_021D56F4 = 0x00000030u;
    uint32_t _ea_021D56F4 = _base_021D56F4 + _off_021D56F4;
    uint32_t _post_021D56F4 = _base_021D56F4 + _off_021D56F4;
    { uint32_t _m = runtime_mem_cycles(_ea_021D56F4, 4u, 0u); _cyc_021D56F4 += _m; _data_021D56F4 += _m; }
    uint32_t _v_021D56F4;
    { uint32_t _w = bus_read_u32(_ea_021D56F4 & ~3u); uint32_t _rot = (_ea_021D56F4 & 3u) * 8u; _v_021D56F4 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[0] = _v_021D56F4;
    g_cpu.R[15] = 0x021D56F8u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D56F4, _data_021D56F4, _int_021D56F4, 1u) : arm7_cycle_combine(_cyc_021D56F4, _data_021D56F4, 1u, (_int_021D56F4 != 0u)));
    if (runtime_unwinding()) return;
L_021D56F8:
    /* 021D56F8  021d56f8 A str r0,[r2] */
    g_cpu.R[15] = 0x021D56F8u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D56F8 = 1u;
    uint32_t _code_021D56F8 = nds_code_numc(0x021D56F8u, NDS_ARM9_CODE_K(0x021D56F8u, 0));
    uint32_t _data_021D56F8 = 0u;
    uint32_t _int_021D56F8 = 0u;
    _cyc_021D56F8 = 1u;
    _int_021D56F8 = 0u;
    uint32_t _base_021D56F8 = g_cpu.R[2];
    uint32_t _off_021D56F8;
    _off_021D56F8 = 0x00000000u;
    uint32_t _ea_021D56F8 = _base_021D56F8 + _off_021D56F8;
    uint32_t _post_021D56F8 = _base_021D56F8 + _off_021D56F8;
    { uint32_t _m = runtime_mem_cycles(_ea_021D56F8, 4u, 0u); _cyc_021D56F8 += _m; _data_021D56F8 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D56F8u, _ea_021D56F8 & ~3u, g_cpu.R[0], 4u);
    bus_write_u32(_ea_021D56F8 & ~3u, g_cpu.R[0]);
    g_cpu.R[15] = 0x021D56FCu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D56F8, _data_021D56F8, _int_021D56F8, 1u) : arm7_cycle_combine(_cyc_021D56F8, _data_021D56F8, 0u, (_int_021D56F8 != 0u)));
    if (runtime_unwinding()) return;
L_021D56FC:
    /* 021D56FC  021d56fc A ldr r0,[r1] */
    g_cpu.R[15] = 0x021D56FCu;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D56FC = 1u;
    uint32_t _code_021D56FC = nds_code_numc(0x021D56FCu, NDS_ARM9_CODE_K(0x021D56FCu, 0));
    uint32_t _data_021D56FC = 0u;
    uint32_t _int_021D56FC = 0u;
    _cyc_021D56FC = 2u;
    _int_021D56FC = 0u;
    uint32_t _base_021D56FC = g_cpu.R[1];
    uint32_t _off_021D56FC;
    _off_021D56FC = 0x00000000u;
    uint32_t _ea_021D56FC = _base_021D56FC + _off_021D56FC;
    uint32_t _post_021D56FC = _base_021D56FC + _off_021D56FC;
    { uint32_t _m = runtime_mem_cycles(_ea_021D56FC, 4u, 0u); _cyc_021D56FC += _m; _data_021D56FC += _m; }
    uint32_t _v_021D56FC;
    { uint32_t _w = bus_read_u32(_ea_021D56FC & ~3u); uint32_t _rot = (_ea_021D56FC & 3u) * 8u; _v_021D56FC = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[0] = _v_021D56FC;
    g_cpu.R[15] = 0x021D5700u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D56FC, _data_021D56FC, _int_021D56FC, 1u) : arm7_cycle_combine(_cyc_021D56FC, _data_021D56FC, 1u, (_int_021D56FC != 0u)));
    if (runtime_unwinding()) return;
    /* fall-through to 0x021D5700 */
    g_cpu.R[15] = 0x021D5700u;
    { static NdsLinkSlot _lnk_021D5700_f = {0, 0u, 0x021D5700u, 0};
      runtime_link_fallthrough(&_lnk_021D5700_f); }
    return;
}

/* 0x021D5700  mode=arm  end=0x021D5714  branches=0  indirect */
void por_arm9_021d5000_23b9ff77_afunc_021D5700(void) {
    if (g_cpu.R[15] != 0x021D5700u) {
        switch (g_cpu.R[15]) {
            case 0x021D5704u: goto L_021D5704;
            case 0x021D5708u: goto L_021D5708;
            case 0x021D570Cu: goto L_021D570C;
            case 0x021D5710u: goto L_021D5710;
            default: runtime_dispatch_bad_entry(g_cpu.R[15]); return;
        }
    }
L_021D5700:
    /* 021D5700  021d5700 A add r0,r0,#0x1b000 */
    g_cpu.R[15] = 0x021D5700u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5700 = 1u;
    uint32_t _code_021D5700 = nds_code_numc(0x021D5700u, NDS_ARM9_CODE_K(0x021D5700u, 0));
    uint32_t _data_021D5700 = 0u;
    uint32_t _int_021D5700 = 0u;
    _cyc_021D5700 = 1u;
    _int_021D5700 = 0u;
    uint32_t _rn_021D5700 = g_cpu.R[0];
    uint32_t _r_021D5700;
    _r_021D5700 = _rn_021D5700 + 0x0001B000u;
    g_cpu.R[0] = _r_021D5700;
    g_cpu.R[15] = 0x021D5704u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5700, _data_021D5700, _int_021D5700, 0u) : arm7_cycle_combine(_cyc_021D5700, _data_021D5700, 0u, (_int_021D5700 != 0u)));
    if (runtime_unwinding()) return;
L_021D5704:
    /* 021D5704  021d5704 A ldr r0,[r0,#0x790] */
    g_cpu.R[15] = 0x021D5704u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5704 = 1u;
    uint32_t _code_021D5704 = nds_code_numc(0x021D5704u, NDS_ARM9_CODE_K(0x021D5704u, 0));
    uint32_t _data_021D5704 = 0u;
    uint32_t _int_021D5704 = 0u;
    _cyc_021D5704 = 2u;
    _int_021D5704 = 0u;
    uint32_t _base_021D5704 = g_cpu.R[0];
    uint32_t _off_021D5704;
    _off_021D5704 = 0x00000790u;
    uint32_t _ea_021D5704 = _base_021D5704 + _off_021D5704;
    uint32_t _post_021D5704 = _base_021D5704 + _off_021D5704;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5704, 4u, 0u); _cyc_021D5704 += _m; _data_021D5704 += _m; }
    uint32_t _v_021D5704;
    { uint32_t _w = bus_read_u32(_ea_021D5704 & ~3u); uint32_t _rot = (_ea_021D5704 & 3u) * 8u; _v_021D5704 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[0] = _v_021D5704;
    g_cpu.R[15] = 0x021D5708u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5704, _data_021D5704, _int_021D5704, 1u) : arm7_cycle_combine(_cyc_021D5704, _data_021D5704, 1u, (_int_021D5704 != 0u)));
    if (runtime_unwinding()) return;
L_021D5708:
    /* 021D5708  021d5708 A add r0,r0,#0x60000 */
    g_cpu.R[15] = 0x021D5708u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5708 = 1u;
    uint32_t _code_021D5708 = nds_code_numc(0x021D5708u, NDS_ARM9_CODE_K(0x021D5708u, 0));
    uint32_t _data_021D5708 = 0u;
    uint32_t _int_021D5708 = 0u;
    _cyc_021D5708 = 1u;
    _int_021D5708 = 0u;
    uint32_t _rn_021D5708 = g_cpu.R[0];
    uint32_t _r_021D5708;
    _r_021D5708 = _rn_021D5708 + 0x00060000u;
    g_cpu.R[0] = _r_021D5708;
    g_cpu.R[15] = 0x021D570Cu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5708, _data_021D5708, _int_021D5708, 0u) : arm7_cycle_combine(_cyc_021D5708, _data_021D5708, 0u, (_int_021D5708 != 0u)));
    if (runtime_unwinding()) return;
L_021D570C:
    /* 021D570C  021d570c A str r0,[r2,#0x4] */
    g_cpu.R[15] = 0x021D570Cu;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D570C = 1u;
    uint32_t _code_021D570C = nds_code_numc(0x021D570Cu, NDS_ARM9_CODE_K(0x021D570Cu, 0));
    uint32_t _data_021D570C = 0u;
    uint32_t _int_021D570C = 0u;
    _cyc_021D570C = 1u;
    _int_021D570C = 0u;
    uint32_t _base_021D570C = g_cpu.R[2];
    uint32_t _off_021D570C;
    _off_021D570C = 0x00000004u;
    uint32_t _ea_021D570C = _base_021D570C + _off_021D570C;
    uint32_t _post_021D570C = _base_021D570C + _off_021D570C;
    { uint32_t _m = runtime_mem_cycles(_ea_021D570C, 4u, 0u); _cyc_021D570C += _m; _data_021D570C += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D570Cu, _ea_021D570C & ~3u, g_cpu.R[0], 4u);
    bus_write_u32(_ea_021D570C & ~3u, g_cpu.R[0]);
    g_cpu.R[15] = 0x021D5710u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D570C, _data_021D570C, _int_021D570C, 1u) : arm7_cycle_combine(_cyc_021D570C, _data_021D570C, 0u, (_int_021D570C != 0u)));
    if (runtime_unwinding()) return;
L_021D5710:
    /* 021D5710  021d5710 A bx r14 */
    g_cpu.R[15] = 0x021D5710u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5710 = 1u;
    uint32_t _code_021D5710 = nds_code_numc(0x021D5710u, NDS_ARM9_CODE_K(0x021D5710u, 0));
    uint32_t _data_021D5710 = 0u;
    uint32_t _int_021D5710 = 0u;
    _cyc_021D5710 = 3u;
    _int_021D5710 = 0u;
    uint32_t _bxt_021D5710 = g_cpu.R[14];
    g_cpu.R[15] = _bxt_021D5710 & ((_bxt_021D5710 & 1u) ? ~1u : ~3u);
    if (_bxt_021D5710 & 1u) g_cpu.cpsr |= CPSR_T_BIT; else g_cpu.cpsr &= ~CPSR_T_BIT;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_refill_cycles(_bxt_021D5710) : arm7_refill_cycles(_bxt_021D5710));
    if (runtime_unwinding()) return;
    if (runtime_call_should_return(g_cpu.R[15])) return;
    runtime_dispatch_with_exchange(_bxt_021D5710);
    return;
    g_cpu.R[15] = 0x021D5714u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5710, _data_021D5710, _int_021D5710, 0u) : arm7_cycle_combine(_cyc_021D5710, _data_021D5710, 0u, (_int_021D5710 != 0u)));
    if (runtime_unwinding()) return;
    /* fall-through to 0x021D5714 */
    g_cpu.R[15] = 0x021D5714u;
    { static NdsLinkSlot _lnk_021D5714_f = {0, 0u, 0x021D5714u, 0};
      runtime_link_fallthrough(&_lnk_021D5714_f); }
    return;
}

/* 0x021D5DE8  mode=arm  end=0x021D5E24  branches=0  indirect */
void por_arm9_021d5000_23b9ff77_afunc_021D5DE8(void) {
    if (g_cpu.R[15] != 0x021D5DE8u) {
        switch (g_cpu.R[15]) {
            case 0x021D5DECu: goto L_021D5DEC;
            case 0x021D5DF0u: goto L_021D5DF0;
            case 0x021D5DF4u: goto L_021D5DF4;
            case 0x021D5DF8u: goto L_021D5DF8;
            case 0x021D5DFCu: goto L_021D5DFC;
            case 0x021D5E00u: goto L_021D5E00;
            case 0x021D5E04u: goto L_021D5E04;
            case 0x021D5E08u: goto L_021D5E08;
            case 0x021D5E0Cu: goto L_021D5E0C;
            case 0x021D5E10u: goto L_021D5E10;
            case 0x021D5E14u: goto L_021D5E14;
            case 0x021D5E18u: goto L_021D5E18;
            case 0x021D5E1Cu: goto L_021D5E1C;
            case 0x021D5E20u: goto L_021D5E20;
            default: runtime_dispatch_bad_entry(g_cpu.R[15]); return;
        }
    }
L_021D5DE8:
    /* 021D5DE8  021d5de8 A ldr r1,[r15,#0x34] */
    g_cpu.R[15] = 0x021D5DE8u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5DE8 = 1u;
    uint32_t _code_021D5DE8 = nds_code_numc(0x021D5DE8u, NDS_ARM9_CODE_K(0x021D5DE8u, 0));
    uint32_t _data_021D5DE8 = 0u;
    uint32_t _int_021D5DE8 = 0u;
    _cyc_021D5DE8 = 2u;
    _int_021D5DE8 = 0u;
    uint32_t _base_021D5DE8 = 0x021D5DF0u;
    uint32_t _off_021D5DE8;
    _off_021D5DE8 = 0x00000034u;
    uint32_t _ea_021D5DE8 = _base_021D5DE8 + _off_021D5DE8;
    uint32_t _post_021D5DE8 = _base_021D5DE8 + _off_021D5DE8;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5DE8, 4u, 0u); _cyc_021D5DE8 += _m; _data_021D5DE8 += _m; }
    uint32_t _v_021D5DE8;
    { uint32_t _w = bus_read_u32(_ea_021D5DE8 & ~3u); uint32_t _rot = (_ea_021D5DE8 & 3u) * 8u; _v_021D5DE8 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[1] = _v_021D5DE8;
    g_cpu.R[15] = 0x021D5DECu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5DE8, _data_021D5DE8, _int_021D5DE8, 1u) : arm7_cycle_combine(_cyc_021D5DE8, _data_021D5DE8, 1u, (_int_021D5DE8 != 0u)));
    if (runtime_unwinding()) return;
L_021D5DEC:
    /* 021D5DEC  021d5dec A ldr r2,[r0,#0x158] */
    g_cpu.R[15] = 0x021D5DECu;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5DEC = 1u;
    uint32_t _code_021D5DEC = nds_code_numc(0x021D5DECu, NDS_ARM9_CODE_K(0x021D5DECu, 0));
    uint32_t _data_021D5DEC = 0u;
    uint32_t _int_021D5DEC = 0u;
    _cyc_021D5DEC = 2u;
    _int_021D5DEC = 0u;
    uint32_t _base_021D5DEC = g_cpu.R[0];
    uint32_t _off_021D5DEC;
    _off_021D5DEC = 0x00000158u;
    uint32_t _ea_021D5DEC = _base_021D5DEC + _off_021D5DEC;
    uint32_t _post_021D5DEC = _base_021D5DEC + _off_021D5DEC;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5DEC, 4u, 0u); _cyc_021D5DEC += _m; _data_021D5DEC += _m; }
    uint32_t _v_021D5DEC;
    { uint32_t _w = bus_read_u32(_ea_021D5DEC & ~3u); uint32_t _rot = (_ea_021D5DEC & 3u) * 8u; _v_021D5DEC = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[2] = _v_021D5DEC;
    g_cpu.R[15] = 0x021D5DF0u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5DEC, _data_021D5DEC, _int_021D5DEC, 1u) : arm7_cycle_combine(_cyc_021D5DEC, _data_021D5DEC, 1u, (_int_021D5DEC != 0u)));
    if (runtime_unwinding()) return;
L_021D5DF0:
    /* 021D5DF0  021d5df0 A ldr r0,[r1] */
    g_cpu.R[15] = 0x021D5DF0u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5DF0 = 1u;
    uint32_t _code_021D5DF0 = nds_code_numc(0x021D5DF0u, NDS_ARM9_CODE_K(0x021D5DF0u, 0));
    uint32_t _data_021D5DF0 = 0u;
    uint32_t _int_021D5DF0 = 0u;
    _cyc_021D5DF0 = 2u;
    _int_021D5DF0 = 0u;
    uint32_t _base_021D5DF0 = g_cpu.R[1];
    uint32_t _off_021D5DF0;
    _off_021D5DF0 = 0x00000000u;
    uint32_t _ea_021D5DF0 = _base_021D5DF0 + _off_021D5DF0;
    uint32_t _post_021D5DF0 = _base_021D5DF0 + _off_021D5DF0;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5DF0, 4u, 0u); _cyc_021D5DF0 += _m; _data_021D5DF0 += _m; }
    uint32_t _v_021D5DF0;
    { uint32_t _w = bus_read_u32(_ea_021D5DF0 & ~3u); uint32_t _rot = (_ea_021D5DF0 & 3u) * 8u; _v_021D5DF0 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[0] = _v_021D5DF0;
    g_cpu.R[15] = 0x021D5DF4u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5DF0, _data_021D5DF0, _int_021D5DF0, 1u) : arm7_cycle_combine(_cyc_021D5DF0, _data_021D5DF0, 1u, (_int_021D5DF0 != 0u)));
    if (runtime_unwinding()) return;
L_021D5DF4:
    /* 021D5DF4  021d5df4 A add r0,r0,#0x1b000 */
    g_cpu.R[15] = 0x021D5DF4u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5DF4 = 1u;
    uint32_t _code_021D5DF4 = nds_code_numc(0x021D5DF4u, NDS_ARM9_CODE_K(0x021D5DF4u, 0));
    uint32_t _data_021D5DF4 = 0u;
    uint32_t _int_021D5DF4 = 0u;
    _cyc_021D5DF4 = 1u;
    _int_021D5DF4 = 0u;
    uint32_t _rn_021D5DF4 = g_cpu.R[0];
    uint32_t _r_021D5DF4;
    _r_021D5DF4 = _rn_021D5DF4 + 0x0001B000u;
    g_cpu.R[0] = _r_021D5DF4;
    g_cpu.R[15] = 0x021D5DF8u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5DF4, _data_021D5DF4, _int_021D5DF4, 0u) : arm7_cycle_combine(_cyc_021D5DF4, _data_021D5DF4, 0u, (_int_021D5DF4 != 0u)));
    if (runtime_unwinding()) return;
L_021D5DF8:
    /* 021D5DF8  021d5df8 A ldrb r0,[r0,#0xce7] */
    g_cpu.R[15] = 0x021D5DF8u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5DF8 = 1u;
    uint32_t _code_021D5DF8 = nds_code_numc(0x021D5DF8u, NDS_ARM9_CODE_K(0x021D5DF8u, 0));
    uint32_t _data_021D5DF8 = 0u;
    uint32_t _int_021D5DF8 = 0u;
    _cyc_021D5DF8 = 2u;
    _int_021D5DF8 = 0u;
    uint32_t _base_021D5DF8 = g_cpu.R[0];
    uint32_t _off_021D5DF8;
    _off_021D5DF8 = 0x00000CE7u;
    uint32_t _ea_021D5DF8 = _base_021D5DF8 + _off_021D5DF8;
    uint32_t _post_021D5DF8 = _base_021D5DF8 + _off_021D5DF8;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5DF8, 1u, 0u); _cyc_021D5DF8 += _m; _data_021D5DF8 += _m; }
    uint32_t _v_021D5DF8;
    _v_021D5DF8 = bus_read_u8(_ea_021D5DF8);
    g_cpu.R[0] = _v_021D5DF8;
    g_cpu.R[15] = 0x021D5DFCu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5DF8, _data_021D5DF8, _int_021D5DF8, 1u) : arm7_cycle_combine(_cyc_021D5DF8, _data_021D5DF8, 1u, (_int_021D5DF8 != 0u)));
    if (runtime_unwinding()) return;
L_021D5DFC:
    /* 021D5DFC  021d5dfc A strb r0,[r2,#0x6c] */
    g_cpu.R[15] = 0x021D5DFCu;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5DFC = 1u;
    uint32_t _code_021D5DFC = nds_code_numc(0x021D5DFCu, NDS_ARM9_CODE_K(0x021D5DFCu, 0));
    uint32_t _data_021D5DFC = 0u;
    uint32_t _int_021D5DFC = 0u;
    _cyc_021D5DFC = 1u;
    _int_021D5DFC = 0u;
    uint32_t _base_021D5DFC = g_cpu.R[2];
    uint32_t _off_021D5DFC;
    _off_021D5DFC = 0x0000006Cu;
    uint32_t _ea_021D5DFC = _base_021D5DFC + _off_021D5DFC;
    uint32_t _post_021D5DFC = _base_021D5DFC + _off_021D5DFC;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5DFC, 1u, 0u); _cyc_021D5DFC += _m; _data_021D5DFC += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5DFCu, _ea_021D5DFC, (uint32_t)(g_cpu.R[0] & 0xFFu), 1u);
    bus_write_u8(_ea_021D5DFC, (uint8_t)(g_cpu.R[0] & 0xFFu));
    g_cpu.R[15] = 0x021D5E00u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5DFC, _data_021D5DFC, _int_021D5DFC, 1u) : arm7_cycle_combine(_cyc_021D5DFC, _data_021D5DFC, 0u, (_int_021D5DFC != 0u)));
    if (runtime_unwinding()) return;
L_021D5E00:
    /* 021D5E00  021d5e00 A ldr r0,[r1] */
    g_cpu.R[15] = 0x021D5E00u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5E00 = 1u;
    uint32_t _code_021D5E00 = nds_code_numc(0x021D5E00u, NDS_ARM9_CODE_K(0x021D5E00u, 0));
    uint32_t _data_021D5E00 = 0u;
    uint32_t _int_021D5E00 = 0u;
    _cyc_021D5E00 = 2u;
    _int_021D5E00 = 0u;
    uint32_t _base_021D5E00 = g_cpu.R[1];
    uint32_t _off_021D5E00;
    _off_021D5E00 = 0x00000000u;
    uint32_t _ea_021D5E00 = _base_021D5E00 + _off_021D5E00;
    uint32_t _post_021D5E00 = _base_021D5E00 + _off_021D5E00;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5E00, 4u, 0u); _cyc_021D5E00 += _m; _data_021D5E00 += _m; }
    uint32_t _v_021D5E00;
    { uint32_t _w = bus_read_u32(_ea_021D5E00 & ~3u); uint32_t _rot = (_ea_021D5E00 & 3u) * 8u; _v_021D5E00 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[0] = _v_021D5E00;
    g_cpu.R[15] = 0x021D5E04u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5E00, _data_021D5E00, _int_021D5E00, 1u) : arm7_cycle_combine(_cyc_021D5E00, _data_021D5E00, 1u, (_int_021D5E00 != 0u)));
    if (runtime_unwinding()) return;
L_021D5E04:
    /* 021D5E04  021d5e04 A add r0,r0,#0x1b000 */
    g_cpu.R[15] = 0x021D5E04u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5E04 = 1u;
    uint32_t _code_021D5E04 = nds_code_numc(0x021D5E04u, NDS_ARM9_CODE_K(0x021D5E04u, 0));
    uint32_t _data_021D5E04 = 0u;
    uint32_t _int_021D5E04 = 0u;
    _cyc_021D5E04 = 1u;
    _int_021D5E04 = 0u;
    uint32_t _rn_021D5E04 = g_cpu.R[0];
    uint32_t _r_021D5E04;
    _r_021D5E04 = _rn_021D5E04 + 0x0001B000u;
    g_cpu.R[0] = _r_021D5E04;
    g_cpu.R[15] = 0x021D5E08u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5E04, _data_021D5E04, _int_021D5E04, 0u) : arm7_cycle_combine(_cyc_021D5E04, _data_021D5E04, 0u, (_int_021D5E04 != 0u)));
    if (runtime_unwinding()) return;
L_021D5E08:
    /* 021D5E08  021d5e08 A ldr r0,[r0,#0xd2c] */
    g_cpu.R[15] = 0x021D5E08u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5E08 = 1u;
    uint32_t _code_021D5E08 = nds_code_numc(0x021D5E08u, NDS_ARM9_CODE_K(0x021D5E08u, 0));
    uint32_t _data_021D5E08 = 0u;
    uint32_t _int_021D5E08 = 0u;
    _cyc_021D5E08 = 2u;
    _int_021D5E08 = 0u;
    uint32_t _base_021D5E08 = g_cpu.R[0];
    uint32_t _off_021D5E08;
    _off_021D5E08 = 0x00000D2Cu;
    uint32_t _ea_021D5E08 = _base_021D5E08 + _off_021D5E08;
    uint32_t _post_021D5E08 = _base_021D5E08 + _off_021D5E08;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5E08, 4u, 0u); _cyc_021D5E08 += _m; _data_021D5E08 += _m; }
    uint32_t _v_021D5E08;
    { uint32_t _w = bus_read_u32(_ea_021D5E08 & ~3u); uint32_t _rot = (_ea_021D5E08 & 3u) * 8u; _v_021D5E08 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[0] = _v_021D5E08;
    g_cpu.R[15] = 0x021D5E0Cu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5E08, _data_021D5E08, _int_021D5E08, 1u) : arm7_cycle_combine(_cyc_021D5E08, _data_021D5E08, 1u, (_int_021D5E08 != 0u)));
    if (runtime_unwinding()) return;
L_021D5E0C:
    /* 021D5E0C  021d5e0c A ldr r0,[r0,#0xe0] */
    g_cpu.R[15] = 0x021D5E0Cu;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5E0C = 1u;
    uint32_t _code_021D5E0C = nds_code_numc(0x021D5E0Cu, NDS_ARM9_CODE_K(0x021D5E0Cu, 0));
    uint32_t _data_021D5E0C = 0u;
    uint32_t _int_021D5E0C = 0u;
    _cyc_021D5E0C = 2u;
    _int_021D5E0C = 0u;
    uint32_t _base_021D5E0C = g_cpu.R[0];
    uint32_t _off_021D5E0C;
    _off_021D5E0C = 0x000000E0u;
    uint32_t _ea_021D5E0C = _base_021D5E0C + _off_021D5E0C;
    uint32_t _post_021D5E0C = _base_021D5E0C + _off_021D5E0C;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5E0C, 4u, 0u); _cyc_021D5E0C += _m; _data_021D5E0C += _m; }
    uint32_t _v_021D5E0C;
    { uint32_t _w = bus_read_u32(_ea_021D5E0C & ~3u); uint32_t _rot = (_ea_021D5E0C & 3u) * 8u; _v_021D5E0C = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[0] = _v_021D5E0C;
    g_cpu.R[15] = 0x021D5E10u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5E0C, _data_021D5E0C, _int_021D5E0C, 1u) : arm7_cycle_combine(_cyc_021D5E0C, _data_021D5E0C, 1u, (_int_021D5E0C != 0u)));
    if (runtime_unwinding()) return;
L_021D5E10:
    /* 021D5E10  021d5e10 A ands r0,r0,#0x20 */
    g_cpu.R[15] = 0x021D5E10u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5E10 = 1u;
    uint32_t _code_021D5E10 = nds_code_numc(0x021D5E10u, NDS_ARM9_CODE_K(0x021D5E10u, 0));
    uint32_t _data_021D5E10 = 0u;
    uint32_t _int_021D5E10 = 0u;
    _cyc_021D5E10 = 1u;
    _int_021D5E10 = 0u;
    uint32_t _rn_021D5E10 = g_cpu.R[0];
    uint32_t _r_021D5E10;
    _r_021D5E10 = _rn_021D5E10 & 0x00000020u;
    arm_set_nzc_logic(_r_021D5E10, cpsr_c());
    g_cpu.R[0] = _r_021D5E10;
    g_cpu.R[15] = 0x021D5E14u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5E10, _data_021D5E10, _int_021D5E10, 0u) : arm7_cycle_combine(_cyc_021D5E10, _data_021D5E10, 0u, (_int_021D5E10 != 0u)));
    if (runtime_unwinding()) return;
L_021D5E14:
    /* 021D5E14  021d5e14 A movne r0,#0x1 */
    g_cpu.R[15] = 0x021D5E14u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5E14 = 1u;
    uint32_t _code_021D5E14 = nds_code_numc(0x021D5E14u, NDS_ARM9_CODE_K(0x021D5E14u, 0));
    uint32_t _data_021D5E14 = 0u;
    uint32_t _int_021D5E14 = 0u;
    if (arm_cond_passes_i(0x1u)) {
        _cyc_021D5E14 = 1u;
        _int_021D5E14 = 0u;
        uint32_t _r_021D5E14;
        _r_021D5E14 = 0x00000001u;
        g_cpu.R[0] = _r_021D5E14;
    }
    g_cpu.R[15] = 0x021D5E18u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5E14, _data_021D5E14, _int_021D5E14, 0u) : arm7_cycle_combine(_cyc_021D5E14, _data_021D5E14, 0u, (_int_021D5E14 != 0u)));
    if (runtime_unwinding()) return;
L_021D5E18:
    /* 021D5E18  021d5e18 A moveq r0,#0x0 */
    g_cpu.R[15] = 0x021D5E18u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5E18 = 1u;
    uint32_t _code_021D5E18 = nds_code_numc(0x021D5E18u, NDS_ARM9_CODE_K(0x021D5E18u, 0));
    uint32_t _data_021D5E18 = 0u;
    uint32_t _int_021D5E18 = 0u;
    if (arm_cond_passes_i(0x0u)) {
        _cyc_021D5E18 = 1u;
        _int_021D5E18 = 0u;
        uint32_t _r_021D5E18;
        _r_021D5E18 = 0x00000000u;
        g_cpu.R[0] = _r_021D5E18;
    }
    g_cpu.R[15] = 0x021D5E1Cu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5E18, _data_021D5E18, _int_021D5E18, 0u) : arm7_cycle_combine(_cyc_021D5E18, _data_021D5E18, 0u, (_int_021D5E18 != 0u)));
    if (runtime_unwinding()) return;
L_021D5E1C:
    /* 021D5E1C  021d5e1c A strb r0,[r2,#0x6d] */
    g_cpu.R[15] = 0x021D5E1Cu;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5E1C = 1u;
    uint32_t _code_021D5E1C = nds_code_numc(0x021D5E1Cu, NDS_ARM9_CODE_K(0x021D5E1Cu, 0));
    uint32_t _data_021D5E1C = 0u;
    uint32_t _int_021D5E1C = 0u;
    _cyc_021D5E1C = 1u;
    _int_021D5E1C = 0u;
    uint32_t _base_021D5E1C = g_cpu.R[2];
    uint32_t _off_021D5E1C;
    _off_021D5E1C = 0x0000006Du;
    uint32_t _ea_021D5E1C = _base_021D5E1C + _off_021D5E1C;
    uint32_t _post_021D5E1C = _base_021D5E1C + _off_021D5E1C;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5E1C, 1u, 0u); _cyc_021D5E1C += _m; _data_021D5E1C += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5E1Cu, _ea_021D5E1C, (uint32_t)(g_cpu.R[0] & 0xFFu), 1u);
    bus_write_u8(_ea_021D5E1C, (uint8_t)(g_cpu.R[0] & 0xFFu));
    g_cpu.R[15] = 0x021D5E20u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5E1C, _data_021D5E1C, _int_021D5E1C, 1u) : arm7_cycle_combine(_cyc_021D5E1C, _data_021D5E1C, 0u, (_int_021D5E1C != 0u)));
    if (runtime_unwinding()) return;
L_021D5E20:
    /* 021D5E20  021d5e20 A bx r14 */
    g_cpu.R[15] = 0x021D5E20u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5E20 = 1u;
    uint32_t _code_021D5E20 = nds_code_numc(0x021D5E20u, NDS_ARM9_CODE_K(0x021D5E20u, 0));
    uint32_t _data_021D5E20 = 0u;
    uint32_t _int_021D5E20 = 0u;
    _cyc_021D5E20 = 3u;
    _int_021D5E20 = 0u;
    uint32_t _bxt_021D5E20 = g_cpu.R[14];
    g_cpu.R[15] = _bxt_021D5E20 & ((_bxt_021D5E20 & 1u) ? ~1u : ~3u);
    if (_bxt_021D5E20 & 1u) g_cpu.cpsr |= CPSR_T_BIT; else g_cpu.cpsr &= ~CPSR_T_BIT;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_refill_cycles(_bxt_021D5E20) : arm7_refill_cycles(_bxt_021D5E20));
    if (runtime_unwinding()) return;
    if (runtime_call_should_return(g_cpu.R[15])) return;
    runtime_dispatch_with_exchange(_bxt_021D5E20);
    return;
    g_cpu.R[15] = 0x021D5E24u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5E20, _data_021D5E20, _int_021D5E20, 0u) : arm7_cycle_combine(_cyc_021D5E20, _data_021D5E20, 0u, (_int_021D5E20 != 0u)));
    if (runtime_unwinding()) return;
    /* fall-through to 0x021D5E24 */
    g_cpu.R[15] = 0x021D5E24u;
    { static NdsLinkSlot _lnk_021D5E24_f = {0, 0u, 0x021D5E24u, 0};
      runtime_link_fallthrough(&_lnk_021D5E24_f); }
    return;
}

/* 0x021D5FE4  mode=arm  end=0x021D5FFC  branches=1  indirect */
void por_arm9_021d5000_23b9ff77_afunc_021D5FE4(void) {
    if (g_cpu.R[15] != 0x021D5FE4u) {
        switch (g_cpu.R[15]) {
            case 0x021D5FE8u: goto L_021D5FE8;
            case 0x021D5FECu: goto L_021D5FEC;
            case 0x021D5FF0u: goto L_021D5FF0;
            case 0x021D5FF4u: goto L_021D5FF4;
            case 0x021D5FF8u: goto L_021D5FF8;
            default: runtime_dispatch_bad_entry(g_cpu.R[15]); return;
        }
    }
L_021D5FE4:
    /* 021D5FE4  021d5fe4 A stm r13!,{r4,r5,r6,r7,r8,r14} */
    g_cpu.R[15] = 0x021D5FE4u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FE4 = 1u;
    uint32_t _code_021D5FE4 = nds_code_numc(0x021D5FE4u, NDS_ARM9_CODE_K(0x021D5FE4u, 0));
    uint32_t _data_021D5FE4 = 0u;
    uint32_t _int_021D5FE4 = 0u;
    _cyc_021D5FE4 = 1u;
    _int_021D5FE4 = 0u;
    uint32_t _b_021D5FE4 = g_cpu.R[13];
    uint32_t _a_021D5FE4 = _b_021D5FE4 - 24u;
    uint32_t _fb_021D5FE4 = _b_021D5FE4 - 24u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 0u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[4], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[4]);
    _a_021D5FE4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 1u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[5], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[5]);
    _a_021D5FE4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 1u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[6], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[6]);
    _a_021D5FE4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 1u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[7], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[7]);
    _a_021D5FE4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 1u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[8], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[8]);
    _a_021D5FE4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 1u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[14], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[14]);
    _a_021D5FE4 += 4u;
    g_cpu.R[13] = _fb_021D5FE4;
    g_cpu.R[15] = 0x021D5FE8u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FE4, _data_021D5FE4, _int_021D5FE4, 1u) : arm7_cycle_combine(_cyc_021D5FE4, _data_021D5FE4, 0u, (_int_021D5FE4 != 0u)));
    if (runtime_unwinding()) return;
L_021D5FE8:
    /* 021D5FE8  021d5fe8 A mov r8,r0 */
    g_cpu.R[15] = 0x021D5FE8u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FE8 = 1u;
    uint32_t _code_021D5FE8 = nds_code_numc(0x021D5FE8u, NDS_ARM9_CODE_K(0x021D5FE8u, 0));
    uint32_t _data_021D5FE8 = 0u;
    uint32_t _int_021D5FE8 = 0u;
    _cyc_021D5FE8 = 1u;
    _int_021D5FE8 = 0u;
    uint32_t _rm_021D5FE8 = g_cpu.R[0];
    uint32_t _op2_021D5FE8;
    uint32_t _co_021D5FE8;
    _op2_021D5FE8 = _rm_021D5FE8;
    _co_021D5FE8 = cpsr_c();
    uint32_t _r_021D5FE8;
    _r_021D5FE8 = _op2_021D5FE8;
    g_cpu.R[8] = _r_021D5FE8;
    g_cpu.R[15] = 0x021D5FECu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FE8, _data_021D5FE8, _int_021D5FE8, 0u) : arm7_cycle_combine(_cyc_021D5FE8, _data_021D5FE8, 0u, (_int_021D5FE8 != 0u)));
    if (runtime_unwinding()) return;
L_021D5FEC:
    /* 021D5FEC  021d5fec A ldrsb r1,[r8,#0x21] */
    g_cpu.R[15] = 0x021D5FECu;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FEC = 1u;
    uint32_t _code_021D5FEC = nds_code_numc(0x021D5FECu, NDS_ARM9_CODE_K(0x021D5FECu, 0));
    uint32_t _data_021D5FEC = 0u;
    uint32_t _int_021D5FEC = 0u;
    _cyc_021D5FEC = 2u;
    _int_021D5FEC = 0u;
    uint32_t _base_021D5FEC = g_cpu.R[8];
    uint32_t _off_021D5FEC;
    _off_021D5FEC = 0x00000021u;
    uint32_t _ea_021D5FEC = _base_021D5FEC + _off_021D5FEC;
    uint32_t _post_021D5FEC = _base_021D5FEC + _off_021D5FEC;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5FEC, 1u, 0u); _cyc_021D5FEC += _m; _data_021D5FEC += _m; }
    uint32_t _v_021D5FEC;
    _v_021D5FEC = (uint32_t)(int32_t)(int8_t)bus_read_u8(_ea_021D5FEC);
    g_cpu.R[1] = _v_021D5FEC;
    g_cpu.R[15] = 0x021D5FF0u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FEC, _data_021D5FEC, _int_021D5FEC, 1u) : arm7_cycle_combine(_cyc_021D5FEC, _data_021D5FEC, 1u, (_int_021D5FEC != 0u)));
    if (runtime_unwinding()) return;
L_021D5FF0:
    /* 021D5FF0  021d5ff0 A ldr r7,[r8,#0x158] */
    g_cpu.R[15] = 0x021D5FF0u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FF0 = 1u;
    uint32_t _code_021D5FF0 = nds_code_numc(0x021D5FF0u, NDS_ARM9_CODE_K(0x021D5FF0u, 0));
    uint32_t _data_021D5FF0 = 0u;
    uint32_t _int_021D5FF0 = 0u;
    _cyc_021D5FF0 = 2u;
    _int_021D5FF0 = 0u;
    uint32_t _base_021D5FF0 = g_cpu.R[8];
    uint32_t _off_021D5FF0;
    _off_021D5FF0 = 0x00000158u;
    uint32_t _ea_021D5FF0 = _base_021D5FF0 + _off_021D5FF0;
    uint32_t _post_021D5FF0 = _base_021D5FF0 + _off_021D5FF0;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5FF0, 4u, 0u); _cyc_021D5FF0 += _m; _data_021D5FF0 += _m; }
    uint32_t _v_021D5FF0;
    { uint32_t _w = bus_read_u32(_ea_021D5FF0 & ~3u); uint32_t _rot = (_ea_021D5FF0 & 3u) * 8u; _v_021D5FF0 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[7] = _v_021D5FF0;
    g_cpu.R[15] = 0x021D5FF4u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FF0, _data_021D5FF0, _int_021D5FF0, 1u) : arm7_cycle_combine(_cyc_021D5FF0, _data_021D5FF0, 1u, (_int_021D5FF0 != 0u)));
    if (runtime_unwinding()) return;
L_021D5FF4:
    /* 021D5FF4  021d5ff4 A cmps r1,#0x0 */
    g_cpu.R[15] = 0x021D5FF4u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FF4 = 1u;
    uint32_t _code_021D5FF4 = nds_code_numc(0x021D5FF4u, NDS_ARM9_CODE_K(0x021D5FF4u, 0));
    uint32_t _data_021D5FF4 = 0u;
    uint32_t _int_021D5FF4 = 0u;
    _cyc_021D5FF4 = 1u;
    _int_021D5FF4 = 0u;
    uint32_t _rn_021D5FF4 = g_cpu.R[1];
    uint32_t _r_021D5FF4;
    _r_021D5FF4 = _rn_021D5FF4 - 0x00000000u;
    arm_set_nzcv_sub(_rn_021D5FF4, 0x00000000u, _r_021D5FF4);
    g_cpu.R[15] = 0x021D5FF8u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FF4, _data_021D5FF4, _int_021D5FF4, 0u) : arm7_cycle_combine(_cyc_021D5FF4, _data_021D5FF4, 0u, (_int_021D5FF4 != 0u)));
    if (runtime_unwinding()) return;
L_021D5FF8:
    /* 021D5FF8  021d5ff8 A ldmeq r13!,{r4,r5,r6,r7,r8,r15} */
    g_cpu.R[15] = 0x021D5FF8u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FF8 = 1u;
    uint32_t _code_021D5FF8 = nds_code_numc(0x021D5FF8u, NDS_ARM9_CODE_K(0x021D5FF8u, 0));
    uint32_t _data_021D5FF8 = 0u;
    uint32_t _int_021D5FF8 = 0u;
    if (arm_cond_passes_i(0x0u)) {
        _cyc_021D5FF8 = 4u;
        _int_021D5FF8 = 0u;
        uint32_t _b_021D5FF8 = g_cpu.R[13];
        uint32_t _a_021D5FF8 = _b_021D5FF8;
        uint32_t _fb_021D5FF8 = _b_021D5FF8 + 24u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 0u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        g_cpu.R[4] = bus_read_u32(_a_021D5FF8 & ~3u);
        _a_021D5FF8 += 4u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 1u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        g_cpu.R[5] = bus_read_u32(_a_021D5FF8 & ~3u);
        _a_021D5FF8 += 4u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 1u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        g_cpu.R[6] = bus_read_u32(_a_021D5FF8 & ~3u);
        _a_021D5FF8 += 4u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 1u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        g_cpu.R[7] = bus_read_u32(_a_021D5FF8 & ~3u);
        _a_021D5FF8 += 4u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 1u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        g_cpu.R[8] = bus_read_u32(_a_021D5FF8 & ~3u);
        _a_021D5FF8 += 4u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 1u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        uint32_t _pc_021D5FF8 = bus_read_u32(_a_021D5FF8 & ~3u);
        g_cpu.R[15] = _pc_021D5FF8 & ~1u;
        if (_pc_021D5FF8 & 1u) g_cpu.cpsr |= CPSR_T_BIT; else g_cpu.cpsr &= ~CPSR_T_BIT;
        _a_021D5FF8 += 4u;
        g_cpu.R[13] = _fb_021D5FF8;
        runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FF8, _data_021D5FF8, _int_021D5FF8, 1u) + arm9_refill_cycles(_pc_021D5FF8) : arm7_cycle_combine(_cyc_021D5FF8, _data_021D5FF8, 1u, (_int_021D5FF8 != 0u)) + arm7_refill_cycles(_pc_021D5FF8));
        if (runtime_unwinding()) return;
        if (runtime_call_should_return(g_cpu.R[15])) return;
        runtime_dispatch_with_exchange(_pc_021D5FF8);
        return;
    }
    g_cpu.R[15] = 0x021D5FFCu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FF8, _data_021D5FF8, _int_021D5FF8, 1u) : arm7_cycle_combine(_cyc_021D5FF8, _data_021D5FF8, 1u, (_int_021D5FF8 != 0u)));
    if (runtime_unwinding()) return;
    /* fall-through to 0x021D5FFC */
    g_cpu.R[15] = 0x021D5FFCu;
    { static NdsLinkSlot _lnk_021D5FFC_f = {0, 0u, 0x021D5FFCu, 0};
      runtime_link_fallthrough(&_lnk_021D5FFC_f); }
    return;
}

/* 0x021D5FFC  mode=arm  end=0x021D6000  branches=1 */
void por_arm9_021d5000_23b9ff77_afunc_021D5FFC(void) {
    if (g_cpu.R[15] != 0x021D5FFCu) {
        switch (g_cpu.R[15]) {
            default: runtime_dispatch_bad_entry(g_cpu.R[15]); return;
        }
    }
L_021D5FFC:
    /* 021D5FFC  021d5ffc A bl 0x021e2804 */
    g_cpu.R[15] = 0x021D5FFCu;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FFC = 1u;
    uint32_t _code_021D5FFC = nds_code_numc(0x021D5FFCu, NDS_ARM9_CODE_K(0x021D5FFCu, 0));
    uint32_t _data_021D5FFC = 0u;
    uint32_t _int_021D5FFC = 0u;
    _cyc_021D5FFC = 3u;
    _int_021D5FFC = 0u;
    g_cpu.R[14] = 0x021D6000u;
    g_cpu.R[15] = 0x021E2804u;
    runtime_call_push_return(0x021D6000u);
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_refill_cycles(0x021E2804u) : arm7_refill_cycles(0x021E2804u));
    if (runtime_unwinding()) return;
    _cyc_021D5FFC = 0u; _code_021D5FFC = 0u; _data_021D5FFC = 0u; _int_021D5FFC = 0u;
    { static NdsLinkSlot _lnk_021D5FFC_c = {0, 0u, 0x021E2804u, 0};
      runtime_link_call(&_lnk_021D5FFC_c); }
    if (runtime_unwinding()) return;
    if (g_cpu.R[15] != 0x021D6000u) { runtime_call_cancel_return(0x021D6000u); return; }
    g_cpu.R[15] = 0x021D6000u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FFC, _data_021D5FFC, _int_021D5FFC, 0u) : arm7_cycle_combine(_cyc_021D5FFC, _data_021D5FFC, 0u, (_int_021D5FFC != 0u)));
    if (runtime_unwinding()) return;
    /* fall-through to 0x021D6000 */
    g_cpu.R[15] = 0x021D6000u;
    { static NdsLinkSlot _lnk_021D6000_f = {0, 0u, 0x021D6000u, 0};
      runtime_link_fallthrough(&_lnk_021D6000_f); }
    return;
}

