/* AUTO-GENERATED by nds_recompile. DO NOT EDIT. */
#ifndef POR_ARM9_022E5000_CCC70063_H
#define POR_ARM9_022E5000_CCC70063_H

/* Total functions: 50 */

void por_arm9_022e5000_ccc70063_afunc_022E5340(void);  /* 0x022E5340 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5370(void);  /* 0x022E5370 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5374(void);  /* 0x022E5374 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5378(void);  /* 0x022E5378 arm */
void por_arm9_022e5000_ccc70063_afunc_022E537C(void);  /* 0x022E537C arm */
void por_arm9_022e5000_ccc70063_afunc_022E5380(void);  /* 0x022E5380 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5384(void);  /* 0x022E5384 arm */
void por_arm9_022e5000_ccc70063_afunc_022E538C(void);  /* 0x022E538C arm */
void por_arm9_022e5000_ccc70063_afunc_022E5398(void);  /* 0x022E5398 arm */
void por_arm9_022e5000_ccc70063_afunc_022E53A8(void);  /* 0x022E53A8 arm */
void por_arm9_022e5000_ccc70063_afunc_022E53AC(void);  /* 0x022E53AC arm */
void por_arm9_022e5000_ccc70063_afunc_022E53B4(void);  /* 0x022E53B4 arm */
void por_arm9_022e5000_ccc70063_afunc_022E53B8(void);  /* 0x022E53B8 arm */
void por_arm9_022e5000_ccc70063_afunc_022E53D8(void);  /* 0x022E53D8 arm */
void por_arm9_022e5000_ccc70063_afunc_022E53E0(void);  /* 0x022E53E0 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5400(void);  /* 0x022E5400 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5408(void);  /* 0x022E5408 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5428(void);  /* 0x022E5428 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5454(void);  /* 0x022E5454 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5470(void);  /* 0x022E5470 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5480(void);  /* 0x022E5480 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5484(void);  /* 0x022E5484 arm */
void por_arm9_022e5000_ccc70063_afunc_022E549C(void);  /* 0x022E549C arm */
void por_arm9_022e5000_ccc70063_afunc_022E54B0(void);  /* 0x022E54B0 arm */
void por_arm9_022e5000_ccc70063_afunc_022E54B4(void);  /* 0x022E54B4 arm */
void por_arm9_022e5000_ccc70063_afunc_022E54D4(void);  /* 0x022E54D4 arm */
void por_arm9_022e5000_ccc70063_afunc_022E54F4(void);  /* 0x022E54F4 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5518(void);  /* 0x022E5518 arm */
void por_arm9_022e5000_ccc70063_afunc_022E551C(void);  /* 0x022E551C arm */
void por_arm9_022e5000_ccc70063_afunc_022E5520(void);  /* 0x022E5520 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5524(void);  /* 0x022E5524 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5528(void);  /* 0x022E5528 arm */
void por_arm9_022e5000_ccc70063_afunc_022E552C(void);  /* 0x022E552C arm */
void por_arm9_022e5000_ccc70063_afunc_022E554C(void);  /* 0x022E554C arm */
void por_arm9_022e5000_ccc70063_afunc_022E5570(void);  /* 0x022E5570 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5578(void);  /* 0x022E5578 arm */
void por_arm9_022e5000_ccc70063_afunc_022E558C(void);  /* 0x022E558C arm */
void por_arm9_022e5000_ccc70063_afunc_022E55A4(void);  /* 0x022E55A4 arm */
void por_arm9_022e5000_ccc70063_afunc_022E55A8(void);  /* 0x022E55A8 arm */
void por_arm9_022e5000_ccc70063_afunc_022E55D0(void);  /* 0x022E55D0 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5620(void);  /* 0x022E5620 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5634(void);  /* 0x022E5634 arm */
void por_arm9_022e5000_ccc70063_afunc_022E564C(void);  /* 0x022E564C arm */
void por_arm9_022e5000_ccc70063_afunc_022E5650(void);  /* 0x022E5650 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5658(void);  /* 0x022E5658 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5680(void);  /* 0x022E5680 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5698(void);  /* 0x022E5698 arm */
void por_arm9_022e5000_ccc70063_afunc_022E56AC(void);  /* 0x022E56AC arm */
void por_arm9_022e5000_ccc70063_afunc_022E56F8(void);  /* 0x022E56F8 arm */
void por_arm9_022e5000_ccc70063_afunc_022E5710(void);  /* 0x022E5710 arm */

#endif /* POR_ARM9_022E5000_CCC70063_H */
