/* AUTO-GENERATED by nds_recompile. DO NOT EDIT. */
/* {guest addr, thumb-bit, generated fn} sorted by address; the
   runtime binary-searches by (addr, CPSR.T) per CPU. */
#include "runtime_arm.h"
#include "por_arm9_021d5000_7eb6cab5.h"

const NdsDispatchEntry g_dispatch_por_arm9_021d5000_7eb6cab5[] = {
    {0x021D5FE4u, 0u, por_arm9_021d5000_7eb6cab5_afunc_021D5FE4, 0},
    {0x021D5FE8u, 0u, por_arm9_021d5000_7eb6cab5_afunc_021D5FE4, 0},
    {0x021D5FECu, 0u, por_arm9_021d5000_7eb6cab5_afunc_021D5FE4, 0},
    {0x021D5FF0u, 0u, por_arm9_021d5000_7eb6cab5_afunc_021D5FE4, 0},
    {0x021D5FF4u, 0u, por_arm9_021d5000_7eb6cab5_afunc_021D5FE4, 0},
    {0x021D5FF8u, 0u, por_arm9_021d5000_7eb6cab5_afunc_021D5FE4, 0},
    {0x021D5FFCu, 0u, por_arm9_021d5000_7eb6cab5_afunc_021D5FFC, 0},
};
const unsigned g_dispatch_por_arm9_021d5000_7eb6cab5_len = 7u;
