/* AUTO-GENERATED by nds_recompile. DO NOT EDIT. */
#ifndef POR_ARM9_022DC000_7519F2ED_H
#define POR_ARM9_022DC000_7519F2ED_H

/* Total functions: 73 */

void por_arm9_022dc000_7519f2ed_afunc_022DC940(void);  /* 0x022DC940 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DC964(void);  /* 0x022DC964 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DC97C(void);  /* 0x022DC97C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DC988(void);  /* 0x022DC988 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DC994(void);  /* 0x022DC994 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DC99C(void);  /* 0x022DC99C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DC9B4(void);  /* 0x022DC9B4 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DC9C8(void);  /* 0x022DC9C8 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DC9E0(void);  /* 0x022DC9E0 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCA04(void);  /* 0x022DCA04 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCA0C(void);  /* 0x022DCA0C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCA4C(void);  /* 0x022DCA4C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCA64(void);  /* 0x022DCA64 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCA70(void);  /* 0x022DCA70 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCA7C(void);  /* 0x022DCA7C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCA80(void);  /* 0x022DCA80 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCA84(void);  /* 0x022DCA84 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCA98(void);  /* 0x022DCA98 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCAB0(void);  /* 0x022DCAB0 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCABC(void);  /* 0x022DCABC arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCADC(void);  /* 0x022DCADC arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCAF0(void);  /* 0x022DCAF0 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCB30(void);  /* 0x022DCB30 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCB38(void);  /* 0x022DCB38 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCB50(void);  /* 0x022DCB50 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCB70(void);  /* 0x022DCB70 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCB78(void);  /* 0x022DCB78 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCB8C(void);  /* 0x022DCB8C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCB94(void);  /* 0x022DCB94 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCB98(void);  /* 0x022DCB98 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCBA0(void);  /* 0x022DCBA0 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCBB0(void);  /* 0x022DCBB0 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCBC0(void);  /* 0x022DCBC0 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCBC4(void);  /* 0x022DCBC4 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCBC8(void);  /* 0x022DCBC8 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCBCC(void);  /* 0x022DCBCC arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCBD0(void);  /* 0x022DCBD0 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCBF0(void);  /* 0x022DCBF0 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCBF4(void);  /* 0x022DCBF4 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCBF8(void);  /* 0x022DCBF8 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC00(void);  /* 0x022DCC00 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC04(void);  /* 0x022DCC04 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC0C(void);  /* 0x022DCC0C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC10(void);  /* 0x022DCC10 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC24(void);  /* 0x022DCC24 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC38(void);  /* 0x022DCC38 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC3C(void);  /* 0x022DCC3C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC44(void);  /* 0x022DCC44 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC4C(void);  /* 0x022DCC4C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC5C(void);  /* 0x022DCC5C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC80(void);  /* 0x022DCC80 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC84(void);  /* 0x022DCC84 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC8C(void);  /* 0x022DCC8C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC94(void);  /* 0x022DCC94 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCC98(void);  /* 0x022DCC98 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCCA8(void);  /* 0x022DCCA8 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCCAC(void);  /* 0x022DCCAC arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCCB4(void);  /* 0x022DCCB4 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCCBC(void);  /* 0x022DCCBC arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCCD4(void);  /* 0x022DCCD4 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCCE4(void);  /* 0x022DCCE4 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCCE8(void);  /* 0x022DCCE8 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCCF4(void);  /* 0x022DCCF4 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCCF8(void);  /* 0x022DCCF8 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCCFC(void);  /* 0x022DCCFC arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCD00(void);  /* 0x022DCD00 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCD08(void);  /* 0x022DCD08 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCD0C(void);  /* 0x022DCD0C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCD14(void);  /* 0x022DCD14 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCD3C(void);  /* 0x022DCD3C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCD4C(void);  /* 0x022DCD4C arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCD50(void);  /* 0x022DCD50 arm */
void por_arm9_022dc000_7519f2ed_afunc_022DCD58(void);  /* 0x022DCD58 arm */

#endif /* POR_ARM9_022DC000_7519F2ED_H */
