/* AUTO-GENERATED by nds_recompile. DO NOT EDIT. */
#ifndef POR_ARM9_021D5000_7EB6CAB5_H
#define POR_ARM9_021D5000_7EB6CAB5_H

/* Total functions: 2 */

void por_arm9_021d5000_7eb6cab5_afunc_021D5FE4(void);  /* 0x021D5FE4 arm */
void por_arm9_021d5000_7eb6cab5_afunc_021D5FFC(void);  /* 0x021D5FFC arm */

#endif /* POR_ARM9_021D5000_7EB6CAB5_H */
