/* AUTO-GENERATED by nds_recompile. DO NOT EDIT.
   Each guest function lowers to a void C function over the recomp
   ABI (g_cpu, bus_*, runtime_*; see runtime_arm.h). The interpreter
   is never consulted at runtime — an unlowered op aborts via
   runtime_unimplemented_op (PRINCIPLES.md). */
#include "runtime_arm.h"

void por_arm9_01ffe000_2f2fa648_afunc_01FFE0D4(void);

/* 0x01FFE0D4  mode=arm  end=0x01FFE0DC  branches=0  indirect */
void por_arm9_01ffe000_2f2fa648_afunc_01FFE0D4(void) {
    if (g_cpu.R[15] != 0x01FFE0D4u) {
        switch (g_cpu.R[15]) {
            case 0x01FFE0D8u: goto L_01FFE0D8;
            default: runtime_dispatch_bad_entry(g_cpu.R[15]); return;
        }
    }
L_01FFE0D4:
    /* 01FFE0D4  01ffe0d4 A ldm r13!,{r4,r5,r6,r7,r8,r9,r10,r11,r12,r14} */
    g_cpu.R[15] = 0x01FFE0D4u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_01FFE0D4 = 1u;
    uint32_t _code_01FFE0D4 = nds_code_numc(0x01FFE0D4u, NDS_ARM9_CODE_K(0x01FFE0D4u, 0));
    uint32_t _data_01FFE0D4 = 0u;
    uint32_t _int_01FFE0D4 = 0u;
    _cyc_01FFE0D4 = 2u;
    _int_01FFE0D4 = 0u;
    uint32_t _b_01FFE0D4 = g_cpu.R[13];
    uint32_t _a_01FFE0D4 = _b_01FFE0D4;
    uint32_t _fb_01FFE0D4 = _b_01FFE0D4 + 40u;
    { uint32_t _m = runtime_mem_cycles(_a_01FFE0D4 & ~3u, 4u, 0u); _cyc_01FFE0D4 += _m; _data_01FFE0D4 += _m; }
    g_cpu.R[4] = bus_read_u32(_a_01FFE0D4 & ~3u);
    _a_01FFE0D4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_01FFE0D4 & ~3u, 4u, 1u); _cyc_01FFE0D4 += _m; _data_01FFE0D4 += _m; }
    g_cpu.R[5] = bus_read_u32(_a_01FFE0D4 & ~3u);
    _a_01FFE0D4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_01FFE0D4 & ~3u, 4u, 1u); _cyc_01FFE0D4 += _m; _data_01FFE0D4 += _m; }
    g_cpu.R[6] = bus_read_u32(_a_01FFE0D4 & ~3u);
    _a_01FFE0D4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_01FFE0D4 & ~3u, 4u, 1u); _cyc_01FFE0D4 += _m; _data_01FFE0D4 += _m; }
    g_cpu.R[7] = bus_read_u32(_a_01FFE0D4 & ~3u);
    _a_01FFE0D4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_01FFE0D4 & ~3u, 4u, 1u); _cyc_01FFE0D4 += _m; _data_01FFE0D4 += _m; }
    g_cpu.R[8] = bus_read_u32(_a_01FFE0D4 & ~3u);
    _a_01FFE0D4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_01FFE0D4 & ~3u, 4u, 1u); _cyc_01FFE0D4 += _m; _data_01FFE0D4 += _m; }
    g_cpu.R[9] = bus_read_u32(_a_01FFE0D4 & ~3u);
    _a_01FFE0D4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_01FFE0D4 & ~3u, 4u, 1u); _cyc_01FFE0D4 += _m; _data_01FFE0D4 += _m; }
    g_cpu.R[10] = bus_read_u32(_a_01FFE0D4 & ~3u);
    _a_01FFE0D4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_01FFE0D4 & ~3u, 4u, 1u); _cyc_01FFE0D4 += _m; _data_01FFE0D4 += _m; }
    g_cpu.R[11] = bus_read_u32(_a_01FFE0D4 & ~3u);
    _a_01FFE0D4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_01FFE0D4 & ~3u, 4u, 1u); _cyc_01FFE0D4 += _m; _data_01FFE0D4 += _m; }
    g_cpu.R[12] = bus_read_u32(_a_01FFE0D4 & ~3u);
    _a_01FFE0D4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_01FFE0D4 & ~3u, 4u, 1u); _cyc_01FFE0D4 += _m; _data_01FFE0D4 += _m; }
    g_cpu.R[14] = bus_read_u32(_a_01FFE0D4 & ~3u);
    _a_01FFE0D4 += 4u;
    g_cpu.R[13] = _fb_01FFE0D4;
    g_cpu.R[15] = 0x01FFE0D8u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_01FFE0D4, _data_01FFE0D4, _int_01FFE0D4, 1u) : arm7_cycle_combine(_cyc_01FFE0D4, _data_01FFE0D4, 1u, (_int_01FFE0D4 != 0u)));
    if (runtime_unwinding()) return;
L_01FFE0D8:
    /* 01FFE0D8  01ffe0d8 A bx r14 */
    g_cpu.R[15] = 0x01FFE0D8u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_01FFE0D8 = 1u;
    uint32_t _code_01FFE0D8 = nds_code_numc(0x01FFE0D8u, NDS_ARM9_CODE_K(0x01FFE0D8u, 0));
    uint32_t _data_01FFE0D8 = 0u;
    uint32_t _int_01FFE0D8 = 0u;
    _cyc_01FFE0D8 = 3u;
    _int_01FFE0D8 = 0u;
    uint32_t _bxt_01FFE0D8 = g_cpu.R[14];
    g_cpu.R[15] = _bxt_01FFE0D8 & ((_bxt_01FFE0D8 & 1u) ? ~1u : ~3u);
    if (_bxt_01FFE0D8 & 1u) g_cpu.cpsr |= CPSR_T_BIT; else g_cpu.cpsr &= ~CPSR_T_BIT;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_refill_cycles(_bxt_01FFE0D8) : arm7_refill_cycles(_bxt_01FFE0D8));
    if (runtime_unwinding()) return;
    if (runtime_call_should_return(g_cpu.R[15])) return;
    runtime_dispatch_with_exchange(_bxt_01FFE0D8);
    return;
    g_cpu.R[15] = 0x01FFE0DCu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_01FFE0D8, _data_01FFE0D8, _int_01FFE0D8, 0u) : arm7_cycle_combine(_cyc_01FFE0D8, _data_01FFE0D8, 0u, (_int_01FFE0D8 != 0u)));
    if (runtime_unwinding()) return;
    /* fall-through to 0x01FFE0DC */
    g_cpu.R[15] = 0x01FFE0DCu;
    { static NdsLinkSlot _lnk_01FFE0DC_f = {0, 0u, 0x01FFE0DCu, 0};
      runtime_link_fallthrough(&_lnk_01FFE0DC_f); }
    return;
}

