/* AUTO-GENERATED by nds_recompile. DO NOT EDIT. */
/* {guest addr, thumb-bit, generated fn} sorted by address; the
   runtime binary-searches by (addr, CPSR.T) per CPU. */
#include "runtime_arm.h"
#include "por_arm9_021d5000_23b9ff77.h"

const NdsDispatchEntry g_dispatch_por_arm9_021d5000_23b9ff77[] = {
    {0x021D56E0u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D56E0, 0},
    {0x021D56E4u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D56E0, 0},
    {0x021D56E8u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D56E0, 0},
    {0x021D56ECu, 0u, por_arm9_021d5000_23b9ff77_afunc_021D56E0, 0},
    {0x021D56F0u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D56E0, 0},
    {0x021D56F4u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D56F4, 0},
    {0x021D56F8u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D56F4, 0},
    {0x021D56FCu, 0u, por_arm9_021d5000_23b9ff77_afunc_021D56F4, 0},
    {0x021D5700u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5700, 0},
    {0x021D5704u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5700, 0},
    {0x021D5708u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5700, 0},
    {0x021D570Cu, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5700, 0},
    {0x021D5710u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5700, 0},
    {0x021D5DE8u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5DECu, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5DF0u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5DF4u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5DF8u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5DFCu, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5E00u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5E04u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5E08u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5E0Cu, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5E10u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5E14u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5E18u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5E1Cu, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5E20u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5DE8, 0},
    {0x021D5FE4u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5FE4, 0},
    {0x021D5FE8u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5FE4, 0},
    {0x021D5FECu, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5FE4, 0},
    {0x021D5FF0u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5FE4, 0},
    {0x021D5FF4u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5FE4, 0},
    {0x021D5FF8u, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5FE4, 0},
    {0x021D5FFCu, 0u, por_arm9_021d5000_23b9ff77_afunc_021D5FFC, 0},
};
const unsigned g_dispatch_por_arm9_021d5000_23b9ff77_len = 35u;
