/* AUTO-GENERATED by nds_recompile. DO NOT EDIT. */
#ifndef POR_ARM9_01FFE000_2F2FA648_H
#define POR_ARM9_01FFE000_2F2FA648_H

/* Total functions: 1 */

void por_arm9_01ffe000_2f2fa648_afunc_01FFE0D4(void);  /* 0x01FFE0D4 arm */

#endif /* POR_ARM9_01FFE000_2F2FA648_H */
