/* AUTO-GENERATED by nds_recompile. DO NOT EDIT. */
#ifndef POR_ARM9_021D5000_23B9FF77_H
#define POR_ARM9_021D5000_23B9FF77_H

/* Total functions: 6 */

void por_arm9_021d5000_23b9ff77_afunc_021D56E0(void);  /* 0x021D56E0 arm */
void por_arm9_021d5000_23b9ff77_afunc_021D56F4(void);  /* 0x021D56F4 arm */
void por_arm9_021d5000_23b9ff77_afunc_021D5700(void);  /* 0x021D5700 arm */
void por_arm9_021d5000_23b9ff77_afunc_021D5DE8(void);  /* 0x021D5DE8 arm */
void por_arm9_021d5000_23b9ff77_afunc_021D5FE4(void);  /* 0x021D5FE4 arm */
void por_arm9_021d5000_23b9ff77_afunc_021D5FFC(void);  /* 0x021D5FFC arm */

#endif /* POR_ARM9_021D5000_23B9FF77_H */
