/* AUTO-GENERATED by nds_recompile. DO NOT EDIT. */
#ifndef POR_ARM9_022E5000_E512229C_H
#define POR_ARM9_022E5000_E512229C_H

/* Total functions: 49 */

void por_arm9_022e5000_e512229c_afunc_022E5340(void);  /* 0x022E5340 arm */
void por_arm9_022e5000_e512229c_afunc_022E534C(void);  /* 0x022E534C arm */
void por_arm9_022e5000_e512229c_afunc_022E5354(void);  /* 0x022E5354 arm */
void por_arm9_022e5000_e512229c_afunc_022E5370(void);  /* 0x022E5370 arm */
void por_arm9_022e5000_e512229c_afunc_022E5374(void);  /* 0x022E5374 arm */
void por_arm9_022e5000_e512229c_afunc_022E5378(void);  /* 0x022E5378 arm */
void por_arm9_022e5000_e512229c_afunc_022E537C(void);  /* 0x022E537C arm */
void por_arm9_022e5000_e512229c_afunc_022E5380(void);  /* 0x022E5380 arm */
void por_arm9_022e5000_e512229c_afunc_022E5384(void);  /* 0x022E5384 arm */
void por_arm9_022e5000_e512229c_afunc_022E538C(void);  /* 0x022E538C arm */
void por_arm9_022e5000_e512229c_afunc_022E5394(void);  /* 0x022E5394 arm */
void por_arm9_022e5000_e512229c_afunc_022E53A0(void);  /* 0x022E53A0 arm */
void por_arm9_022e5000_e512229c_afunc_022E53AC(void);  /* 0x022E53AC arm */
void por_arm9_022e5000_e512229c_afunc_022E53B0(void);  /* 0x022E53B0 arm */
void por_arm9_022e5000_e512229c_afunc_022E53C4(void);  /* 0x022E53C4 arm */
void por_arm9_022e5000_e512229c_afunc_022E53CC(void);  /* 0x022E53CC arm */
void por_arm9_022e5000_e512229c_afunc_022E53F0(void);  /* 0x022E53F0 arm */
void por_arm9_022e5000_e512229c_afunc_022E5404(void);  /* 0x022E5404 arm */
void por_arm9_022e5000_e512229c_afunc_022E5410(void);  /* 0x022E5410 arm */
void por_arm9_022e5000_e512229c_afunc_022E5418(void);  /* 0x022E5418 arm */
void por_arm9_022e5000_e512229c_afunc_022E5428(void);  /* 0x022E5428 arm */
void por_arm9_022e5000_e512229c_afunc_022E5430(void);  /* 0x022E5430 arm */
void por_arm9_022e5000_e512229c_afunc_022E5438(void);  /* 0x022E5438 arm */
void por_arm9_022e5000_e512229c_afunc_022E543C(void);  /* 0x022E543C arm */
void por_arm9_022e5000_e512229c_afunc_022E5450(void);  /* 0x022E5450 arm */
void por_arm9_022e5000_e512229c_afunc_022E5458(void);  /* 0x022E5458 arm */
void por_arm9_022e5000_e512229c_afunc_022E5468(void);  /* 0x022E5468 arm */
void por_arm9_022e5000_e512229c_afunc_022E549C(void);  /* 0x022E549C arm */
void por_arm9_022e5000_e512229c_afunc_022E54BC(void);  /* 0x022E54BC arm */
void por_arm9_022e5000_e512229c_afunc_022E54C4(void);  /* 0x022E54C4 arm */
void por_arm9_022e5000_e512229c_afunc_022E54C8(void);  /* 0x022E54C8 arm */
void por_arm9_022e5000_e512229c_afunc_022E54D8(void);  /* 0x022E54D8 arm */
void por_arm9_022e5000_e512229c_afunc_022E54E4(void);  /* 0x022E54E4 arm */
void por_arm9_022e5000_e512229c_afunc_022E54EC(void);  /* 0x022E54EC arm */
void por_arm9_022e5000_e512229c_afunc_022E551C(void);  /* 0x022E551C arm */
void por_arm9_022e5000_e512229c_afunc_022E5520(void);  /* 0x022E5520 arm */
void por_arm9_022e5000_e512229c_afunc_022E5538(void);  /* 0x022E5538 arm */
void por_arm9_022e5000_e512229c_afunc_022E5540(void);  /* 0x022E5540 arm */
void por_arm9_022e5000_e512229c_afunc_022E5548(void);  /* 0x022E5548 arm */
void por_arm9_022e5000_e512229c_afunc_022E5560(void);  /* 0x022E5560 arm */
void por_arm9_022e5000_e512229c_afunc_022E5564(void);  /* 0x022E5564 arm */
void por_arm9_022e5000_e512229c_afunc_022E5570(void);  /* 0x022E5570 arm */
void por_arm9_022e5000_e512229c_afunc_022E5578(void);  /* 0x022E5578 arm */
void por_arm9_022e5000_e512229c_afunc_022E5588(void);  /* 0x022E5588 arm */
void por_arm9_022e5000_e512229c_afunc_022E5594(void);  /* 0x022E5594 arm */
void por_arm9_022e5000_e512229c_afunc_022E55A4(void);  /* 0x022E55A4 arm */
void por_arm9_022e5000_e512229c_afunc_022E55B4(void);  /* 0x022E55B4 arm */
void por_arm9_022e5000_e512229c_afunc_022E55D0(void);  /* 0x022E55D0 arm */
void por_arm9_022e5000_e512229c_afunc_022E55F0(void);  /* 0x022E55F0 arm */

#endif /* POR_ARM9_022E5000_E512229C_H */
