/* AUTO-GENERATED by nds_recompile. DO NOT EDIT. */
/* {guest addr, thumb-bit, generated fn} sorted by address; the
   runtime binary-searches by (addr, CPSR.T) per CPU. */
#include "runtime_arm.h"
#include "por_arm9_01ffe000_2f2fa648.h"

const NdsDispatchEntry g_dispatch_por_arm9_01ffe000_2f2fa648[] = {
    {0x01FFE0D4u, 0u, por_arm9_01ffe000_2f2fa648_afunc_01FFE0D4, 0},
    {0x01FFE0D8u, 0u, por_arm9_01ffe000_2f2fa648_afunc_01FFE0D4, 0},
};
const unsigned g_dispatch_por_arm9_01ffe000_2f2fa648_len = 2u;
