/* AUTO-GENERATED by nds_recompile. DO NOT EDIT.
   Each guest function lowers to a void C function over the recomp
   ABI (g_cpu, bus_*, runtime_*; see runtime_arm.h). The interpreter
   is never consulted at runtime — an unlowered op aborts via
   runtime_unimplemented_op (PRINCIPLES.md). */
#include "runtime_arm.h"

void por_arm9_021d5000_7eb6cab5_afunc_021D5FE4(void);
void por_arm9_021d5000_7eb6cab5_afunc_021D5FFC(void);

/* 0x021D5FE4  mode=arm  end=0x021D5FFC  branches=1  indirect */
void por_arm9_021d5000_7eb6cab5_afunc_021D5FE4(void) {
    if (g_cpu.R[15] != 0x021D5FE4u) {
        switch (g_cpu.R[15]) {
            case 0x021D5FE8u: goto L_021D5FE8;
            case 0x021D5FECu: goto L_021D5FEC;
            case 0x021D5FF0u: goto L_021D5FF0;
            case 0x021D5FF4u: goto L_021D5FF4;
            case 0x021D5FF8u: goto L_021D5FF8;
            default: runtime_dispatch_bad_entry(g_cpu.R[15]); return;
        }
    }
L_021D5FE4:
    /* 021D5FE4  021d5fe4 A stm r13!,{r4,r5,r6,r7,r8,r14} */
    g_cpu.R[15] = 0x021D5FE4u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FE4 = 1u;
    uint32_t _code_021D5FE4 = nds_code_numc(0x021D5FE4u, NDS_ARM9_CODE_K(0x021D5FE4u, 0));
    uint32_t _data_021D5FE4 = 0u;
    uint32_t _int_021D5FE4 = 0u;
    _cyc_021D5FE4 = 1u;
    _int_021D5FE4 = 0u;
    uint32_t _b_021D5FE4 = g_cpu.R[13];
    uint32_t _a_021D5FE4 = _b_021D5FE4 - 24u;
    uint32_t _fb_021D5FE4 = _b_021D5FE4 - 24u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 0u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[4], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[4]);
    _a_021D5FE4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 1u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[5], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[5]);
    _a_021D5FE4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 1u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[6], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[6]);
    _a_021D5FE4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 1u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[7], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[7]);
    _a_021D5FE4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 1u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[8], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[8]);
    _a_021D5FE4 += 4u;
    { uint32_t _m = runtime_mem_cycles(_a_021D5FE4 & ~3u, 4u, 1u); _cyc_021D5FE4 += _m; _data_021D5FE4 += _m; }
    runtime_trace_event(RUNTIME_TRACE_MEM_WRITE, 0x021D5FE4u, _a_021D5FE4 & ~3u, g_cpu.R[14], 4u);
    bus_write_u32(_a_021D5FE4 & ~3u, g_cpu.R[14]);
    _a_021D5FE4 += 4u;
    g_cpu.R[13] = _fb_021D5FE4;
    g_cpu.R[15] = 0x021D5FE8u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FE4, _data_021D5FE4, _int_021D5FE4, 1u) : arm7_cycle_combine(_cyc_021D5FE4, _data_021D5FE4, 0u, (_int_021D5FE4 != 0u)));
    if (runtime_unwinding()) return;
L_021D5FE8:
    /* 021D5FE8  021d5fe8 A mov r8,r0 */
    g_cpu.R[15] = 0x021D5FE8u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FE8 = 1u;
    uint32_t _code_021D5FE8 = nds_code_numc(0x021D5FE8u, NDS_ARM9_CODE_K(0x021D5FE8u, 0));
    uint32_t _data_021D5FE8 = 0u;
    uint32_t _int_021D5FE8 = 0u;
    _cyc_021D5FE8 = 1u;
    _int_021D5FE8 = 0u;
    uint32_t _rm_021D5FE8 = g_cpu.R[0];
    uint32_t _op2_021D5FE8;
    uint32_t _co_021D5FE8;
    _op2_021D5FE8 = _rm_021D5FE8;
    _co_021D5FE8 = cpsr_c();
    uint32_t _r_021D5FE8;
    _r_021D5FE8 = _op2_021D5FE8;
    g_cpu.R[8] = _r_021D5FE8;
    g_cpu.R[15] = 0x021D5FECu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FE8, _data_021D5FE8, _int_021D5FE8, 0u) : arm7_cycle_combine(_cyc_021D5FE8, _data_021D5FE8, 0u, (_int_021D5FE8 != 0u)));
    if (runtime_unwinding()) return;
L_021D5FEC:
    /* 021D5FEC  021d5fec A ldrsb r1,[r8,#0x21] */
    g_cpu.R[15] = 0x021D5FECu;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FEC = 1u;
    uint32_t _code_021D5FEC = nds_code_numc(0x021D5FECu, NDS_ARM9_CODE_K(0x021D5FECu, 0));
    uint32_t _data_021D5FEC = 0u;
    uint32_t _int_021D5FEC = 0u;
    _cyc_021D5FEC = 2u;
    _int_021D5FEC = 0u;
    uint32_t _base_021D5FEC = g_cpu.R[8];
    uint32_t _off_021D5FEC;
    _off_021D5FEC = 0x00000021u;
    uint32_t _ea_021D5FEC = _base_021D5FEC + _off_021D5FEC;
    uint32_t _post_021D5FEC = _base_021D5FEC + _off_021D5FEC;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5FEC, 1u, 0u); _cyc_021D5FEC += _m; _data_021D5FEC += _m; }
    uint32_t _v_021D5FEC;
    _v_021D5FEC = (uint32_t)(int32_t)(int8_t)bus_read_u8(_ea_021D5FEC);
    g_cpu.R[1] = _v_021D5FEC;
    g_cpu.R[15] = 0x021D5FF0u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FEC, _data_021D5FEC, _int_021D5FEC, 1u) : arm7_cycle_combine(_cyc_021D5FEC, _data_021D5FEC, 1u, (_int_021D5FEC != 0u)));
    if (runtime_unwinding()) return;
L_021D5FF0:
    /* 021D5FF0  021d5ff0 A ldr r7,[r8,#0x158] */
    g_cpu.R[15] = 0x021D5FF0u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FF0 = 1u;
    uint32_t _code_021D5FF0 = nds_code_numc(0x021D5FF0u, NDS_ARM9_CODE_K(0x021D5FF0u, 0));
    uint32_t _data_021D5FF0 = 0u;
    uint32_t _int_021D5FF0 = 0u;
    _cyc_021D5FF0 = 2u;
    _int_021D5FF0 = 0u;
    uint32_t _base_021D5FF0 = g_cpu.R[8];
    uint32_t _off_021D5FF0;
    _off_021D5FF0 = 0x00000158u;
    uint32_t _ea_021D5FF0 = _base_021D5FF0 + _off_021D5FF0;
    uint32_t _post_021D5FF0 = _base_021D5FF0 + _off_021D5FF0;
    { uint32_t _m = runtime_mem_cycles(_ea_021D5FF0, 4u, 0u); _cyc_021D5FF0 += _m; _data_021D5FF0 += _m; }
    uint32_t _v_021D5FF0;
    { uint32_t _w = bus_read_u32(_ea_021D5FF0 & ~3u); uint32_t _rot = (_ea_021D5FF0 & 3u) * 8u; _v_021D5FF0 = (_rot == 0u) ? _w : ((_w >> _rot) | (_w << (32u - _rot))); }
    g_cpu.R[7] = _v_021D5FF0;
    g_cpu.R[15] = 0x021D5FF4u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FF0, _data_021D5FF0, _int_021D5FF0, 1u) : arm7_cycle_combine(_cyc_021D5FF0, _data_021D5FF0, 1u, (_int_021D5FF0 != 0u)));
    if (runtime_unwinding()) return;
L_021D5FF4:
    /* 021D5FF4  021d5ff4 A cmps r1,#0x0 */
    g_cpu.R[15] = 0x021D5FF4u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FF4 = 1u;
    uint32_t _code_021D5FF4 = nds_code_numc(0x021D5FF4u, NDS_ARM9_CODE_K(0x021D5FF4u, 0));
    uint32_t _data_021D5FF4 = 0u;
    uint32_t _int_021D5FF4 = 0u;
    _cyc_021D5FF4 = 1u;
    _int_021D5FF4 = 0u;
    uint32_t _rn_021D5FF4 = g_cpu.R[1];
    uint32_t _r_021D5FF4;
    _r_021D5FF4 = _rn_021D5FF4 - 0x00000000u;
    arm_set_nzcv_sub(_rn_021D5FF4, 0x00000000u, _r_021D5FF4);
    g_cpu.R[15] = 0x021D5FF8u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FF4, _data_021D5FF4, _int_021D5FF4, 0u) : arm7_cycle_combine(_cyc_021D5FF4, _data_021D5FF4, 0u, (_int_021D5FF4 != 0u)));
    if (runtime_unwinding()) return;
L_021D5FF8:
    /* 021D5FF8  021d5ff8 A ldmeq r13!,{r4,r5,r6,r7,r8,r15} */
    g_cpu.R[15] = 0x021D5FF8u;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FF8 = 1u;
    uint32_t _code_021D5FF8 = nds_code_numc(0x021D5FF8u, NDS_ARM9_CODE_K(0x021D5FF8u, 0));
    uint32_t _data_021D5FF8 = 0u;
    uint32_t _int_021D5FF8 = 0u;
    if (arm_cond_passes_i(0x0u)) {
        _cyc_021D5FF8 = 4u;
        _int_021D5FF8 = 0u;
        uint32_t _b_021D5FF8 = g_cpu.R[13];
        uint32_t _a_021D5FF8 = _b_021D5FF8;
        uint32_t _fb_021D5FF8 = _b_021D5FF8 + 24u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 0u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        g_cpu.R[4] = bus_read_u32(_a_021D5FF8 & ~3u);
        _a_021D5FF8 += 4u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 1u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        g_cpu.R[5] = bus_read_u32(_a_021D5FF8 & ~3u);
        _a_021D5FF8 += 4u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 1u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        g_cpu.R[6] = bus_read_u32(_a_021D5FF8 & ~3u);
        _a_021D5FF8 += 4u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 1u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        g_cpu.R[7] = bus_read_u32(_a_021D5FF8 & ~3u);
        _a_021D5FF8 += 4u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 1u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        g_cpu.R[8] = bus_read_u32(_a_021D5FF8 & ~3u);
        _a_021D5FF8 += 4u;
        { uint32_t _m = runtime_mem_cycles(_a_021D5FF8 & ~3u, 4u, 1u); _cyc_021D5FF8 += _m; _data_021D5FF8 += _m; }
        uint32_t _pc_021D5FF8 = bus_read_u32(_a_021D5FF8 & ~3u);
        g_cpu.R[15] = _pc_021D5FF8 & ~1u;
        if (_pc_021D5FF8 & 1u) g_cpu.cpsr |= CPSR_T_BIT; else g_cpu.cpsr &= ~CPSR_T_BIT;
        _a_021D5FF8 += 4u;
        g_cpu.R[13] = _fb_021D5FF8;
        runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FF8, _data_021D5FF8, _int_021D5FF8, 1u) + arm9_refill_cycles(_pc_021D5FF8) : arm7_cycle_combine(_cyc_021D5FF8, _data_021D5FF8, 1u, (_int_021D5FF8 != 0u)) + arm7_refill_cycles(_pc_021D5FF8));
        if (runtime_unwinding()) return;
        if (runtime_call_should_return(g_cpu.R[15])) return;
        runtime_dispatch_with_exchange(_pc_021D5FF8);
        return;
    }
    g_cpu.R[15] = 0x021D5FFCu;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FF8, _data_021D5FF8, _int_021D5FF8, 1u) : arm7_cycle_combine(_cyc_021D5FF8, _data_021D5FF8, 1u, (_int_021D5FF8 != 0u)));
    if (runtime_unwinding()) return;
    /* fall-through to 0x021D5FFC */
    g_cpu.R[15] = 0x021D5FFCu;
    { static NdsLinkSlot _lnk_021D5FFC_f = {0, 0u, 0x021D5FFCu, 0};
      runtime_link_fallthrough(&_lnk_021D5FFC_f); }
    return;
}

/* 0x021D5FFC  mode=arm  end=0x021D6000  branches=1 */
void por_arm9_021d5000_7eb6cab5_afunc_021D5FFC(void) {
    if (g_cpu.R[15] != 0x021D5FFCu) {
        switch (g_cpu.R[15]) {
            default: runtime_dispatch_bad_entry(g_cpu.R[15]); return;
        }
    }
L_021D5FFC:
    /* 021D5FFC  021d5ffc A bl 0x021e2804 */
    g_cpu.R[15] = 0x021D5FFCu;
    if (runtime_should_yield()) return;
    ++g_insn_count[g_nds_active];
    if (g_insn_hook_armed) runtime_insn_slow();
    uint32_t _cyc_021D5FFC = 1u;
    uint32_t _code_021D5FFC = nds_code_numc(0x021D5FFCu, NDS_ARM9_CODE_K(0x021D5FFCu, 0));
    uint32_t _data_021D5FFC = 0u;
    uint32_t _int_021D5FFC = 0u;
    _cyc_021D5FFC = 3u;
    _int_021D5FFC = 0u;
    g_cpu.R[14] = 0x021D6000u;
    g_cpu.R[15] = 0x021E2804u;
    runtime_call_push_return(0x021D6000u);
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_refill_cycles(0x021E2804u) : arm7_refill_cycles(0x021E2804u));
    if (runtime_unwinding()) return;
    _cyc_021D5FFC = 0u; _code_021D5FFC = 0u; _data_021D5FFC = 0u; _int_021D5FFC = 0u;
    { static NdsLinkSlot _lnk_021D5FFC_c = {0, 0u, 0x021E2804u, 0};
      runtime_link_call(&_lnk_021D5FFC_c); }
    if (runtime_unwinding()) return;
    if (g_cpu.R[15] != 0x021D6000u) { runtime_call_cancel_return(0x021D6000u); return; }
    g_cpu.R[15] = 0x021D6000u;
    runtime_tick(g_nds_active == NDS_ARM9 ? arm9_cycle_combine(_code_021D5FFC, _data_021D5FFC, _int_021D5FFC, 0u) : arm7_cycle_combine(_cyc_021D5FFC, _data_021D5FFC, 0u, (_int_021D5FFC != 0u)));
    if (runtime_unwinding()) return;
    /* fall-through to 0x021D6000 */
    g_cpu.R[15] = 0x021D6000u;
    { static NdsLinkSlot _lnk_021D6000_f = {0, 0u, 0x021D6000u, 0};
      runtime_link_fallthrough(&_lnk_021D6000_f); }
    return;
}

